<?php
remove_all_actions( 'wp_update_nav_menu_item' );
$menu = 14; $ids = array(); $pos = 0;
$pos++; $ids["Bible Characters"] = wp_update_nav_menu_item( $menu, 0, array( 'menu-item-title' => "Bible Characters", 'menu-item-object' => 'page', 'menu-item-object-id' => 3416, 'menu-item-type' => 'post_type', 'menu-item-status' => 'publish', 'menu-item-parent-id' => 0, 'menu-item-position' => $pos ) );
$pos++; $ids["Old Testament"] = wp_update_nav_menu_item( $menu, 0, array( 'menu-item-title' => "Old Testament", 'menu-item-object' => 'category', 'menu-item-object-id' => 1804, 'menu-item-type' => 'taxonomy', 'menu-item-status' => 'publish', 'menu-item-parent-id' => isset( $ids["Bible Characters"] ) ? $ids["Bible Characters"] : 0, 'menu-item-position' => $pos ) );
$pos++; $ids["New Testament"] = wp_update_nav_menu_item( $menu, 0, array( 'menu-item-title' => "New Testament", 'menu-item-object' => 'category', 'menu-item-object-id' => 1805, 'menu-item-type' => 'taxonomy', 'menu-item-status' => 'publish', 'menu-item-parent-id' => isset( $ids["Bible Characters"] ) ? $ids["Bible Characters"] : 0, 'menu-item-position' => $pos ) );
$pos++; $ids["Bible Maps"] = wp_update_nav_menu_item( $menu, 0, array( 'menu-item-title' => "Bible Maps", 'menu-item-object' => 'post_tag', 'menu-item-object-id' => 1727, 'menu-item-type' => 'taxonomy', 'menu-item-status' => 'publish', 'menu-item-parent-id' => isset( $ids["Bible Characters"] ) ? $ids["Bible Characters"] : 0, 'menu-item-position' => $pos ) );
$pos++; $ids["Leadership"] = wp_update_nav_menu_item( $menu, 0, array( 'menu-item-title' => "Leadership", 'menu-item-object' => 'category', 'menu-item-object-id' => 24, 'menu-item-type' => 'taxonomy', 'menu-item-status' => 'publish', 'menu-item-parent-id' => 0, 'menu-item-position' => $pos ) );
$pos++; $ids["Character & Integrity"] = wp_update_nav_menu_item( $menu, 0, array( 'menu-item-title' => "Character & Integrity", 'menu-item-object' => 'category', 'menu-item-object-id' => 16, 'menu-item-type' => 'taxonomy', 'menu-item-status' => 'publish', 'menu-item-parent-id' => isset( $ids["Leadership"] ) ? $ids["Leadership"] : 0, 'menu-item-position' => $pos ) );
$pos++; $ids["Faith"] = wp_update_nav_menu_item( $menu, 0, array( 'menu-item-title' => "Faith", 'menu-item-object' => 'category', 'menu-item-object-id' => 31, 'menu-item-type' => 'taxonomy', 'menu-item-status' => 'publish', 'menu-item-parent-id' => 0, 'menu-item-position' => $pos ) );
$pos++; $ids["Marketing"] = wp_update_nav_menu_item( $menu, 0, array( 'menu-item-title' => "Marketing", 'menu-item-object' => 'category', 'menu-item-object-id' => 26, 'menu-item-type' => 'taxonomy', 'menu-item-status' => 'publish', 'menu-item-parent-id' => 0, 'menu-item-position' => $pos ) );
$pos++; $ids["Publishing"] = wp_update_nav_menu_item( $menu, 0, array( 'menu-item-title' => "Publishing", 'menu-item-object' => 'category', 'menu-item-object-id' => 30, 'menu-item-type' => 'taxonomy', 'menu-item-status' => 'publish', 'menu-item-parent-id' => isset( $ids["Marketing"] ) ? $ids["Marketing"] : 0, 'menu-item-position' => $pos ) );
$pos++; $ids["Nonprofits & Education"] = wp_update_nav_menu_item( $menu, 0, array( 'menu-item-title' => "Nonprofits & Education", 'menu-item-object' => 'category', 'menu-item-object-id' => 1806, 'menu-item-type' => 'taxonomy', 'menu-item-status' => 'publish', 'menu-item-parent-id' => isset( $ids["Marketing"] ) ? $ids["Marketing"] : 0, 'menu-item-position' => $pos ) );
$pos++; $ids["About"] = wp_update_nav_menu_item( $menu, 0, array( 'menu-item-title' => "About", 'menu-item-object' => 'page', 'menu-item-object-id' => 3393, 'menu-item-type' => 'post_type', 'menu-item-status' => 'publish', 'menu-item-parent-id' => 0, 'menu-item-position' => $pos ) );
$pos++; $ids["Newsletter"] = wp_update_nav_menu_item( $menu, 0, array( 'menu-item-title' => "Newsletter", 'menu-item-object' => 'page', 'menu-item-object-id' => 1464, 'menu-item-type' => 'post_type', 'menu-item-status' => 'publish', 'menu-item-parent-id' => 0, 'menu-item-position' => $pos ) );
