#!/usr/bin/env python3
"""Generate the "in five parts" strip shown after each Bible character post, and push it.

  python3 site/stories.py                 # refresh the data first
  python3 site/story_strip.py [--apply]

Writes site/story-strip-snippet.php (a Code Snippets snippet, front-end scope) with the data
baked in: post id -> the character's song, deep dive, profile and map. It hooks the_content at
priority 15, after wpautop and before the Keep reading block (priority 20), and skips feeds, so
the RSS feed and emails are unchanged. With --apply it lints the PHP, creates or updates the
snippet (id in site/story-strip-snippet-id.txt), activates it and checks a live post.
"""
import json, subprocess, sys
from storykit import DEEP_DIVES, ROOT, SERIES, SITE, check, characters, parts, wp

OUT = ROOT / "site" / "story-strip-snippet.php"
ID_FILE = ROOT / "site" / "story-strip-snippet-id.txt"
LABEL = {"listen": "2. Listen", "deep": "3. Deep dive", "profile": "4. Profile", "map": "5. Map"}  # numbers match the hub
HINT = {"listen": "The song", "deep": "The long version", "profile": "Who they were", "map": "Where it happened"}


def php(v):
    """PHP literal for str / list / dict / None."""
    if v is None:
        return "null"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, str):
        return "'" + v.replace("\\", "\\\\").replace("'", "\\'") + "'"
    if isinstance(v, list):
        return "array(" + ",".join(php(x) for x in v) + ")"
    return "array(" + ",".join(f"{php(k)}=>{php(x)}" for k, x in v.items()) + ")"


def data():
    rows = {}
    for c in characters():
        p = parts(c)
        items = [[k, LABEL[k], HINT[k], p[k][0], p[k][1]] for k in ("listen", "deep", "profile", "map") if k in p and p[k][0]]
        for pid in c["posts"]:
            rows[pid] = [c["name"], items]
    return rows


TEMPLATE = r"""<?php
/**
 * Characters Worth Following: "<name> in five parts" strip after each Bible character post
 * (read, listen, deep dive, profile, map). Generated by site/story_strip.py from site/stories.json;
 * edit those, not this file. Front-end scope. Skips feeds so RSS and emails are unchanged.
 */

if ( ! function_exists( 'ss_story_strip_data' ) ) {

	function ss_story_strip_data() {
		return __DATA__;
	}

	add_filter( 'the_content', function ( $content ) {
		if ( is_feed() || ! is_singular( 'post' ) || ! in_the_loop() || ! is_main_query() ) {
			return $content;
		}
		$all = ss_story_strip_data();
		$id  = get_the_ID();
		if ( ! isset( $all[ $id ] ) ) {
			return $content;
		}
		list( $name, $items ) = $all[ $id ];
		$h  = '<aside class="ss-five" aria-label="' . esc_attr( $name ) . ' in five parts">';
		$h .= '<p class="ss-five-k">__SERIES__</p><h2 class="ss-five-h">' . esc_html( $name ) . ' in five parts</h2><ol class="ss-five-l">';
		$h .= '<li class="is-here"><span class="ss-five-n">1. Read</span><span class="ss-five-d">You just read it</span></li>';
		foreach ( $items as $it ) {
			list( $key, $label, $hint, $href, $detail ) = $it;
			$ext = 0 !== strpos( $href, home_url() );
			$h  .= '<li><span class="ss-five-n">' . esc_html( $label ) . '</span><a class="ss-five-d" href="' . esc_url( $href ) . '"'
				. ( $ext ? ' target="_blank" rel="noopener"' : '' ) . '><small>' . esc_html( $hint ) . '</small>' . esc_html( $detail ) . '</a></li>';
		}
		$h .= '</ol><p class="ss-five-more"><a href="' . esc_url( home_url( '/bible-characters/' ) ) . '">All characters</a> &middot; '
			. '<a href="' . esc_url( home_url( '/songs/' ) ) . '">Songs</a> &middot; <a href="__DEEP__" target="_blank" rel="noopener">Deep dives</a> &middot; '
			. '<a href="' . esc_url( home_url( '/bible-maps/' ) ) . '">Maps</a></p></aside>';
		static $css = false;
		if ( ! $css ) {
			$css = true;
			$h  .= '<style>.ss-five{margin:40px 0 8px;padding:20px 22px;border:1px solid #e6e2d8;border-left:4px solid #dd3333;border-radius:4px;background:#faf8f3}'
				. '.ss-five-k{margin:0;font-size:.72em;font-weight:700;letter-spacing:.1em;text-transform:uppercase;color:#dd3333}'
				. '.ss-five-h{margin:2px 0 14px;font-size:1.3em}'
				. '.ss-five-l{list-style:none;margin:0;padding:0;display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px;}'
				. '.ss-five-l li{display:flex;flex-direction:column;gap:3px;margin:0;padding:10px 12px;background:#fff;border:1px solid #e6e2d8;border-radius:4px}'
				. '.ss-five-n{font-size:.72em;font-weight:700;letter-spacing:.08em;text-transform:uppercase;color:#6b6b6b}'
				. '.ss-five-d{font-weight:700;line-height:1.3;color:#111!important;text-decoration:none!important}'
				. 'a.ss-five-d:hover{color:#dd3333!important}.ss-five-d small{display:block;font-weight:400;font-size:.8em;color:#6b6b6b}'
				. '.is-here{background:#111!important;border-color:#111!important}.is-here .ss-five-n,.is-here .ss-five-d{color:#fff!important}'
				. '.ss-five-more{margin:14px 0 0;font-size:.88em}.ss-five-more a{color:#dd3333}</style>';
		}
		return $content . $h;
	}, 15 );
}
"""


def render():
    d = data()
    code = TEMPLATE.replace("__DATA__", php({int(k): v for k, v in d.items()})).replace("__SERIES__", SERIES).replace("__DEEP__", DEEP_DIVES)
    OUT.write_text(code)
    print(len(d), "posts,", len(code) // 1024, "KB ->", OUT.relative_to(ROOT))
    return code


def apply(code):
    lint = subprocess.run(["php", "-l", str(OUT)], capture_output=True, text=True)
    if lint.returncode:
        sys.exit("php -l failed: " + lint.stdout + lint.stderr)
    body = code.split("<?php", 1)[1].lstrip("\n")
    sid = ID_FILE.read_text().strip() if ID_FILE.exists() else None
    payload = {"name": "Characters Worth Following: five-part strip on posts", "code": body, "scope": "front-end", "active": True,
               "desc": "Generated by site/story_strip.py. Source: site/story-strip-snippet.php."}
    path = f"/code-snippets/v1/snippets/{sid}" if sid else "/code-snippets/v1/snippets"
    code_, res = wp.request("POST", path, json.dumps(payload).encode(), {"Content-Type": "application/json"})
    if code_ not in (200, 201):
        sys.exit(f"snippet save FAILED {code_} {res}")
    ID_FILE.write_text(str(res["id"]) + "\n")
    print("snippet", res["id"], "active" if res.get("active") else "INACTIVE")
    if not res.get("active"):
        wp.request("POST", f"/code-snippets/v1/snippets/{res['id']}/activate")
    ok = check(SITE + "/")  # the site must still load
    sample = next((c for c in characters() if c.get("song") and any(r["status"] == "publish" for r in c.get("post_rows", []))), None)
    if sample:
        link = [r for r in sample["post_rows"] if r["status"] == "publish"][-1]["link"]
        ok = check(link, ('class="ss-five"',)) and ok
    if not ok:
        print("CHECK FAILED: deactivate the snippet if the site is broken")
    return ok


if __name__ == "__main__":
    code = render()
    if "--apply" in sys.argv:
        apply(code)
