-- Dinah, in the format the Claude Project returns (one version, newer songs get two).
-- Run in Supabase > SQL Editor after schema.sql and the five seed-posts files.
begin;
update public.songs set character = $t$Dinah$t$, status = 'ready', chosen_version = null, clips_made_at = null, clip_error = null where post_id = 3149;
delete from public.song_versions where post_id = 3149;
insert into public.song_versions (post_id, version, song_title, format, feel, style, exclude_styles, lyrics, chords, notes) values (3149, 1,
  $t$Let Her Story Be Her Own$t$, 'A', $t$3/4 hymn waltz, D minor to F, final chorus and tag in G, 68 BPM$t$,
  $style$Barbershop quartet, 1940s gospel quartet, close four-part male harmony, warm baritone lead, tenor lock, a cappella-style with light piano and upright bass, slow 3/4 hymn waltz, 66-70 BPM, grave tender minor-key verses, chorus opens into warm major, final chorus modulates up a whole step, reverent and dignified not triumphant, ends with a barbershop tag: ritardando, lead holds the last word while the tenor rises to a high ringing sustained note above the full chord, long fermata, clean stop$style$,
  $t$female vocals, choir, drums, synth, autotune, rap, pop$t$,
  replace($lyrics$[Intro: quartet hums the opening chord softly][[newline]]Mmm...[[newline]][[newline]][Verse 1][[newline]]Jacob's daughter, Leah's child,[[newline]]Went to see the women of the land,[[newline]]Shechem, son of Hamor, took her,[[newline]]And the wrong was by his hand.[[newline]]Then the men began their bargains:[[newline]]Marriage, trade, and title to the ground,[[newline]]Every man had something wanted,[[newline]]But no word of hers is found.[[newline]][[newline]][Chorus: full four-part harmony][[newline]]She's a person, not a pretext,[[newline]]Not a bargain to be made,[[newline]]Not the fuel for someone's fury,[[newline]]Not a debt that must be paid,[[newline]]She is more than what was done to her,[[newline]]Slow down, and listen.[[newline]][[newline]][Verse 2][[newline]]Then her brothers answered Hamor[[newline]]With deceit inside their terms,[[newline]]While the men of Shechem lay healing,[[newline]]Simeon and Levi drew their swords.[[newline]]"Should he treat our sister so?"[[newline]]They shot back to Jacob in their rage,[[newline]]But it never let us hear her,[[newline]]Not one word of hers is on the page.[[newline]][[newline]][Chorus: full four-part harmony][[newline]]She's a person, not a pretext,[[newline]]Not a bargain to be made,[[newline]]Not the fuel for someone's fury,[[newline]]Not a debt that must be paid,[[newline]]She is more than what was done to her,[[newline]]Slow down, and listen.[[newline]][[newline]][Verse 3][[newline]]We can do the same today, friends,[[newline]]When another's wound becomes our case:[[newline]]Tell the details they never offered,[[newline]]Let our anger take their place.[[newline]]Even righteous care stops listening[[newline]]When it only wants to win,[[newline]]Ask her what she needs, respect it,[[newline]]Let her choose where to begin.[[newline]][[newline]][Bridge: softer, lead alone, quartet echoes][[newline]]The wrong was his and never hers, (never hers)[[newline]]Her going out was not the cause, (not the cause)[[newline]]No wedding terms could wash it over,[[newline]]And no sword gave back what was lost.[[newline]]Their anger named a real outrage,[[newline]]But vengeance only multiplied the cost.[[newline]][[newline]][Final Chorus: up a whole step, fuller, all four voices ringing][[newline]]She's a person, not a pretext,[[newline]]Not a bargain to be made,[[newline]]Not the fuel for someone's fury,[[newline]]Not a debt that must be paid,[[newline]]She is more than what was done to her,[[newline]]Slow down, and listen.[[newline]][[newline]][Tag: slow down, full four-part chord, lead holds the last word, tenor rises high above it and holds][[newline]]Let her story, (let her story)[[newline]]Be her own, (be her own)[[newline]]Let her story be her o-o-o-own.[[newline]][[newline]][End: long held final chord, tenor on top, then silence]$lyrics$, '[[newline]]', chr(10)),
  $chords${"bpm": 68, "beats_per_bar": 3, "clips": {"reference": ["verse", "chorus"], "tag": ["tag"]}, "sections": {"verse": {"key": "D minor", "bars": ["Dm", "Dm/C", "Bb", "A7", "Dm", "Gm", "A7", "Dm"]}, "chorus": {"key": "F major", "bars": ["F", "F7", "Bb", "Bbm6", "F/C", "D7", "G7", "C7", "F", "A7", "Dm", "Bb Bbm6", "F/C C7", "F"]}, "bridge": {"key": "D minor to F major", "bars": ["Bb", "C", "Am", "Dm", "Gm7", "C7", "A7", "D7"]}, "final_chorus": {"key": "G major (up a whole step)", "bars": ["G", "G7", "C", "Cm6", "G/D", "E7", "A7", "D7", "G", "B7", "Em", "C Cm6", "G/D D7", "G"]}, "tag": {"key": "G major", "feel": "sustain", "bars": ["C", "Cm6", "G/D", "E7", "A7", "D7", "G~3"]}}}$chords$::jsonb,
  replace($notes$Scripture checked: Genesis 34. Format A: one clear turn (everyone speaks, bargains or takes revenge, and Dinah's own voice never appears).[[newline]]Tender ears: the crime is only 'took her' and 'the wrong'. Genesis 34:31's 'harlot' is paraphrased as 'Should he treat our sister so?'[[newline]]Left out for length: the circumcision condition by name, removing Dinah from Shechem's house, the plunder.[[newline]]Written before the two-version rule, so this post has one version.$notes$, '[[newline]]', chr(10)));
commit;
