#!/usr/bin/env python3
"""Write songs/supabase/seed-posts.sql: every Bible-character post (Old and New Testament
categories, published and scheduled; posts only, never pages) as a row in the songs table,
with the post's plain text as the song's story source.

  python3 songs/supabase/export_posts.py

Priority follows Steve's order: scheduled posts from the latest date backwards, then
published posts from newest to oldest. Re-running only refreshes post fields; it never
touches song fields or status.
"""
import html, json, re, subprocess, sys
from pathlib import Path

CATEGORIES = "1804,1805"  # Old Testament, New Testament
OUT = Path(__file__).with_name("seed-posts.sql")
# Songs made before this pipeline (song.md packages in Steve's Google Drive).
DONE_BEFORE = {
    1854: "Caleb", 1903: "Solomon", 1907: "Hezekiah", 2656: "Nabal", 2642: "Nathan",
    1875: "Shadrach, Meshach, and Abednego",
}


def wp(path):
    out = subprocess.run([sys.executable, "tools/wp.py", "GET", path], capture_output=True, text=True, check=True)
    return json.loads(out.stdout)


def plain_text(raw):
    t = re.sub(r"<!--.*?-->", "", raw, flags=re.S)
    t = re.sub(r"<(script|style)\b.*?</\1>", "", t, flags=re.S | re.I)
    t = re.sub(r"</?(p|h[1-6]|li|blockquote|div|br)\b[^>]*>", "\n", t, flags=re.I)
    t = html.unescape(re.sub(r"<[^>]+>", "", t))
    t = re.sub(r"[ \t]+", " ", t)
    return re.sub(r"\n\s*\n+", "\n\n", t).strip()


def quote(value, tag="q"):
    if value is None:
        return "null"
    s = str(value)
    assert f"${tag}$" not in s
    return f"${tag}${s}${tag}$"


def main():
    posts = {}
    for status in ("future", "publish"):
        page = 1
        while True:
            batch = wp(f"/wp/v2/posts?status={status}&categories={CATEGORIES}&per_page=100&page={page}"
                       "&context=edit&_fields=id,date,date_gmt,slug,link,status,title,content")
            for p in batch:
                posts[p["id"]] = p
            if len(batch) < 100:
                break
            page += 1

    future = sorted((p for p in posts.values() if p["status"] == "future"), key=lambda p: p["date"], reverse=True)
    published = sorted((p for p in posts.values() if p["status"] == "publish"), key=lambda p: p["date"], reverse=True)

    lines = ["-- Generated by songs/supabase/export_posts.py. Paste into Supabase > SQL Editor after schema.sql.",
             f"-- {len(future)} scheduled and {len(published)} published Bible-character posts.", ""]
    for priority, p in enumerate(future + published, start=1):
        character = DONE_BEFORE.get(p["id"])
        lines.append(
            "insert into public.songs (post_id, post_title, post_text, publish_date, post_status, post_url, "
            "priority, character, status) values ("
            f"{p['id']}, {quote(html.unescape(p['title']['raw']))}, "
            f"{quote(plain_text(p['content']['raw']), 'pt')}, {quote(p['date_gmt'] + 'Z')}, "
            f"{quote(p['status'])}, {quote(p['link'])}, {priority}, "
            f"{quote(character)}, {quote('done_before' if character else 'waiting')})\n"
            "on conflict (post_id) do update set post_title = excluded.post_title, post_text = excluded.post_text, "
            "publish_date = excluded.publish_date, post_status = excluded.post_status, "
            "post_url = excluded.post_url, priority = excluded.priority;")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"{OUT}: {len(posts)} posts ({len(future)} scheduled, {len(published)} published), "
          f"{sum(1 for i in posts if i in DONE_BEFORE)} marked done_before")


if __name__ == "__main__":
    main()
