-- Generated by songs/supabase/export_posts.py. Run in Supabase > SQL Editor after schema.sql.
-- 52 scheduled and 46 published Bible-character posts.

-- Part 4 of 5.

insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1873, $q$When Your Boss Wants Your Soul$q$, $q$when-your-boss-wants-your-soul$q$, $pt$BIG IDEA

Some jobs want more than your talent. They want your identity. The question is not whether you will face this pressure. It is whether you will recognize it when it comes.

BACKGROUND

Daniel was a teenager when enemy soldiers dragged him from Jerusalem to Babylon. He spent the next seventy years working for kings who worshipped false gods. He rose to the top. He never bowed.

STORY

In high school, I lived in Iran. One trip took us to Shush — ancient Susa — to the Tomb of Daniel, the site where he has been venerated for over a thousand years. I stood at the tomb of a man who spent his whole career in a system built to own him, and walked out with his soul intact.

Here is how that system worked.

They changed his name.

Day one in Babylon, and the regime erased his identity. Daniel, meaning "God is my judge," became Belteshazzar, meaning "Bel protect the king." A foreign god stamped onto his forehead (Daniel 1:7).

This is how I've watched organizations go after souls. Not with chains. With small surrenders.

And the surrenders come in different packages. Some are obvious. Most are not.

The king's food looked harmless. Premium meals. Executive dining. But Daniel saw it for what it was: a loyalty test. Eating meant belonging. He resolved not to defile himself (Daniel 1:8).

So he drew a line.

Not a loud line. Not a protest. Vegetables and water, please. A refusal that could have cost him everything — the chief official feared the king would have his head over it (Daniel 1:10). Daniel drew it anyway.

I have drawn that line. Years ago I oversaw national TV campaigns, and more than once the agency creatives pitched concepts that leaned on sexual innuendo — sometimes tongue-in-cheek, sometimes direct. When I rejected them outright, the agency didn't shrug and move on. They went over my head. They pleaded to my superiors that I was a prude, working to sabotage my own authority. One time it worked. I was overruled, and the compromise was to take the concepts — one of them flatly R-rated — out to focus groups. The public echoed my original direction. Some went further: they said if that campaign aired, they would never buy from the brand again. Ever.

Drawing the line looked like it cost me nothing. It nearly cost me my seat at the table.

And here is what fascinates me about Daniel. He drew his line and excelled anyway. The king found him ten times better than all the magicians in the realm (Daniel 1:20). I assumed for years that compromise was the price of success. Daniel proved otherwise.

Decades later, rivals tried to destroy him — and the only weapon they could find was his faithfulness. Three times daily, Daniel prayed toward Jerusalem. Windows open. No hiding (Daniel 6:10). The lion's den was supposed to end him. Instead, the king came out proclaiming Daniel's God as the living God (Daniel 6:26).

Daniel's faithfulness did not remove him from Babylon. It positioned him at the center of it. Four kings. Dreams interpreted. Policy shaped. An inner life Babylon could not touch.

The lesson I take is not about food or lions.

It is about knowing which battles to fight. Daniel picked his. He lost the name fight. He won the soul fight. You may not get to keep your title. Keep your heart.$pt$, $q$2026-07-26T16:00:00Z$q$, $q$publish$q$, 61, $q$https://stevesammons.com/when-your-boss-wants-your-soul/$q$, $q$https://sammons.substack.com/p/when-your-boss-wants-your-soul$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1871, $q$Build While They Circle$q$, $q$build-while-they-circle$q$, $pt$BIG IDEA

The best leaders don't wait for perfect conditions.
They build with one hand and hold a sword with the other.
Progress happens when you refuse to come down for your critics.

BACKGROUND

Nehemiah served as cupbearer to the king of Persia. The title sounds like a servant's job. It was a seat of trust beside the most powerful man alive. He gave it up to rebuild a city's broken walls. His story is about leading under pressure while enemies circled (Nehemiah 1–6).

STORY

Here's what nobody told me about building something that matters.

I expected silence. I got sabotage.

Nehemiah learned this the hard way. He left everything to rebuild Jerusalem's walls. Within days, his enemies started mocking. Then they plotted to attack the city (Nehemiah 4:8). Eventually they schemed to harm Nehemiah himself (Nehemiah 6:2).

Most leaders would've called a meeting. Maybe formed a committee. Perhaps asked for better timing.

Not Nehemiah.

He armed his workers. Half built while half stood guard. Every builder wore a sword (Nehemiah 4:17–18).

This is the posture I'm learning to embrace.

Building and defending at the same time. Progress and protection. Creating while critics circle.

I've seen it in my own life. I have long-time friends who say nothing when things are status quo. But when I've stepped into ministries and nonprofits pushing the world toward a better place, they suddenly find their voices. A few have pulled back to the point of alienation. When I take a stand, they get noisy.

Here's what surprised me most: the sword I need isn't for them. It's for my own thoughts. Ridicule from people that close conjures doubts, and the doubts do more damage than the critics ever could. I've caught myself asking, "Were they ever really my friends?" — when the real question is simpler. Is my job to stay focused?

The opposition didn't stop for Nehemiah either. They invited him to "talk things over" four times. Each invitation was a trap (Nehemiah 6:2–4). And the noise came from close — Tobiah had family ties inside Jerusalem itself (Nehemiah 6:17–18). Nehemiah's response is legendary:

"I am doing a great work and I cannot come down."

There it is.

The work itself becomes the answer to every distraction. I'm learning that the mission protects me from meaningless debates — including the ones I hold with myself.

Fifty-two days. That's how fast the wall went up — because Nehemiah wouldn't come down (Nehemiah 6:15).

After the wall was finished, something beautiful happened. The people gathered. They read Scripture aloud for hours. They wept. They celebrated (Nehemiah 8:9–12).

The wall was never really about the wall.

I read those chapters and see something else: space for restoration. For worship. For community to return to its roots.

We're all building something. The critics came for Nehemiah. They've come for most builders I've watched. The invitations to "come down" multiply.

Keep your sword. Keep your trowel. Keep building.$pt$, $q$2026-07-19T16:00:00Z$q$, $q$publish$q$, 62, $q$https://stevesammons.com/build-while-they-circle/$q$, $q$https://sammons.substack.com/p/build-while-they-circle$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1869, $q$The Silent Power of Perfect Timing$q$, $q$the-silent-power-of-perfect-timing$q$, $pt$I don't get to pick my defining hour. Neither did Esther. The question I keep circling isn't whether that moment will come—it's whether I'll be ready when it does.

Background

Esther was a Jewish orphan who became queen of Persia. An unlikely leader with no credentials except courage and timing. Her story shows me that preparation happens in the dark, long before the spotlight found her.

The Story

She had one shot.

One conversation with a king who hadn't asked to see her. One audience that could end in her execution.

The law was clear. Anyone who approached the king uninvited faced death—unless he extended his golden scepter (Esther 4:11).

Esther hadn't been summoned in thirty days.

But her people faced genocide. A decree had been signed. Every Jew in the empire would be destroyed (Esther 3:13).

Her cousin Mordecai sent her a message that changed everything:

"Who knows whether you have come to the kingdom for such a time as this?" (Esther 4:14)

Here's what I missed the first dozen times I read this.

Esther didn't storm in demanding change. She didn't lead with her agenda. She threw a dinner party.

Actually, two dinner parties (Esther 5:4-8).

She waited. Built relationship. Created space for the right moment to emerge.

The leaders I've most wanted to imitate weren't the boldest ones in the room. They were the positioned ones—patient, watching, ready.

Between those two dinners, the king couldn't sleep. He read the royal records. He discovered Mordecai had once saved his life (Esther 6:1-3).

Timing Esther couldn't manufacture. Circumstances no one in the story could orchestrate.

At the second banquet, Esther finally spoke. She revealed the plot. She named the villain. The king acted immediately (Esther 7:3-10).

Her people were saved.

What strikes me about Esther is how her story points beyond itself. A deliverer rises from obscurity. An innocent stands in the gap for the guilty. Someone risks everything so others might live.

Centuries later, another would do the same—not just risking death, but embracing it.

Here's where I have to be honest, though. I may never get an Esther-sized moment. No throne room. No empire hanging on one conversation.

But I've stopped believing that lets me off the hook.

Long before the banquets, Esther was being watched. She won favor with everyone who saw her, back when nothing was at stake (Esther 2:15). The big moment found her because the small ones had already shaped her.

My kids are watching how I react when the day goes sideways. The people in my organization are watching how I behave when I think no one important is in the room.

So I've set a personal goal, and I keep it in front of me every day: I want the distance between how I behave when things are going well and how I behave when things are topsy-turvy to be very close.

How am I when things aren't going my way?

I learned something about that in college, driving a rental car through the desert between LA and Vegas. The tire blew out. I opened the trunk and found the spare flat and shredded. I was renting from a cheap place, and I didn't have much extra money — but I'd expected a spare. What followed was one adversity after another, and a live demonstration, running in my head the whole time, of whether I could keep myself in check.

A phrase surfaced out there that still comes back to me: "Well, didn't want that to happen."

But so what. It happened. Now what — that's the important part.

The world watched Esther.

The world is watching me.

Your "such a time as this" might not be a moment at all. It might be this afternoon, with an audience of one.$pt$, $q$2026-07-12T16:00:00Z$q$, $q$publish$q$, 63, $q$https://stevesammons.com/the-silent-power-of-perfect-timing/$q$, $q$https://sammons.substack.com/p/the-silent-power-of-perfect-timing$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1867, $q$The Outsider Who Changed Everything$q$, $q$the-outsider-who-changed-everything$q$, $pt$BIG IDEA

I keep coming back to the same pattern. The people who changed everything often started on the outside. Wrong family. Wrong place. Wrong everything.

And I've started to wonder if belonging was ever about where we start.

I think it's about what we choose.

BACKGROUND

Ruth was a Moabite. A foreigner from an enemy nation. By every rule she knew, she had reason to walk away.

She didn't.

She made one choice. And we're still talking about it three thousand years later. It put her in the family tree of King David. Then in the family tree of Jesus (Matthew 1:5).

One choice.

STORY

She buried her husband in the only country she'd ever called home.

Then her mother-in-law told her to go. "Go home. Find a new life. You don't owe me anything."

And here's the line I can't get out of my head.

"Where you go, I will go. Your people will be my people. Your God will be my God" (Ruth 1:16).

Read that again.

She had nothing to gain. Her husband was gone. No children. No security. Just an aging widow walking toward a country that would look at Ruth and see an outsider.

She chose loyalty anyway.

I've read this story more times than I can count, and I still miss the most important part.

Ruth didn't wait to be invited. She didn't ask permission to belong. She declared it.

When she reached Bethlehem, she didn't wait around for someone to notice her. She went out to the fields and gathered leftover grain (Ruth 2:2-3). The lowest work there was.

And people noticed anyway.

Boaz was a wealthy landowner. He saw her character before he saw her potential. "I've heard about everything you've done for your mother-in-law," he told her (Ruth 2:11).

A reputation travels faster than a resume.

Ruth had no strategy. No plan to climb. No network. She just showed up. Did the work. Stayed loyal.

And the ending still stuns me.

Through Boaz, she became the great-grandmother of King David (Ruth 4:17). Through David came the Messiah.

A foreign widow. From enemy territory. In the family tree of Christ.

That's not an accident to me. That's the whole point.

I've come to believe God has a habit of choosing outsiders. People who don't fit the profile. People from the wrong place with the wrong story.

So maybe the question was never whether we belong.

Maybe it's whether we're willing to choose.$pt$, $q$2026-07-05T16:00:00Z$q$, $q$publish$q$, 64, $q$https://stevesammons.com/the-outsider-who-changed-everything/$q$, $q$https://sammons.substack.com/p/the-outsider-who-changed-everything$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1901, $q$The Reject They Came Crawling Back For$q$, $q$the-reject-they-came-crawling-back-for$q$, $pt$BIG IDEA

The thing you're most ashamed of might be the thing that makes you a leader.

But watch out. The same fire that makes you strong can burn down your own house.

BACKGROUND

Jephthah lived in Israel about 3,000 years ago. His mother was a prostitute, and his half-brothers never let him forget it. They kicked him out so he couldn't share the family money (Judges 11:1-3).

So he ran. He ended up in a place called Tob.

Where's Tob? Way out past the Jordan River, in the wild country where Jordan and Syria meet today. Think badlands. Empty. Rough. The kind of place people go when nobody wants them.
That's where the story starts.

STORY

Jephthah didn't sit around feeling sorry for himself.

He rounded up other outcasts. Guys nobody else wanted. And he turned them into fighters.

Pretty soon everybody knew his name. Jephthah was tough (Judges 11:3).

Then trouble showed up.

An army called the Ammonites started crushing Israel. The leaders of Gilead got scared. They needed a real fighter.

And they knew exactly who to call.

The same guy they threw away.

So they came crawling back.

Jephthah asked the obvious question. "Didn't you hate me? Didn't you kick me out?" (Judges 11:7)

Good question.

But here's the surprise. He said yes anyway.

We usually think our worst moments ruin us. The times we got left out. The times we got hurt. We figure those years were wasted.

But maybe they weren't.

Out in the badlands, Jephthah learned to lead. He learned to survive. He learned to fight when the odds were terrible.

Those were the exact skills Israel needed.

God's Spirit came on him (Judges 11:29). He beat the Ammonites. The reject became the hero. The Bible even lists him as a hero of faith (Hebrews 11:32).

Now, if this sounds familiar, it should.

Remember Joseph? His brothers threw him away too. But years later he saved them — and forgave them. He hugged them and cried. "You meant it for evil, but God meant it for good" (Genesis 50:20).

Jephthah's story is different.

Nobody came back to say sorry. The leaders only showed up because they needed something. No hugs. No tears. Just a deal.

And here's the part I haven't thought about much.

The same toughness that won the war also got him in trouble. Jephthah made a foolish promise to God — one that broke his own heart and hurt his family (Judges 11:30-40).

The edge that wins the battle can also cut the people you love.

So what does a guy like Jephthah teach me about leading?

Two things.

One: the place where nobody wanted me might be the place that's training me.

Two: being strong isn't enough. The best leaders know when to fight — and when to put the sword down.

Joseph shows me my pain can become my purpose.

Jephthah reminds me my strength needs a soft heart to go with it.

So here's my question.

What if the thing that pushed me out is getting me ready for something I can't see yet?

The people who didn't want me might need me someday.

I need to remember to bring my heart along with the sword.$pt$, $q$2026-06-27T21:00:00Z$q$, $q$publish$q$, 65, $q$https://stevesammons.com/the-reject-they-came-crawling-back-for/$q$, $q$https://sammons.substack.com/p/the-reject-they-came-crawling-back-for$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1854, $q$Give Me the Hard One$q$, $q$give-me-the-hard-one$q$, $pt$There is a difference between chasing difficulty to prove ourselves and choosing a hard task because it is ours to finish.

Caleb (KAY-leb) shows us the second kind.

He was one of twelve men Moses sent to explore Canaan before Israel entered the land. The scouts saw fortified cities and powerful people. Ten concluded that Israel could not succeed. Caleb quieted the crowd and said, “We should go up and take possession of the land, for we can certainly do it” (Numbers 13:30).

Caleb was not ignoring the facts. He had seen the same walls and warriors. His confidence came from what he believed God had promised, not from pretending the obstacles were small.

The people followed the fearful report. That generation spent forty years in the wilderness, and Caleb waited through all of them. God described him as a servant with “a different spirit” who followed wholeheartedly (Numbers 14:24).

Forty-five years after the scouting trip, Caleb came to Joshua. He was now eighty-five. The land was being divided among Israel’s tribes, and Caleb could have asked for a quiet place. Instead, he requested the hill country around Hebron, about twenty miles south of Jerusalem in today’s West Bank (Joshua 14:6–12).

The request was not random. Moses had promised that territory to Caleb because he had remained faithful. The area still had large fortified cities and formidable inhabitants. Caleb was asking to complete an old assignment, not collect an easy reward.

That changes how I hear his words. “Now give me this hill country” is not the boast of a man looking for a fight (Joshua 14:12). It is the resolve of someone who has carried a promise through disappointment, delay, and the death of an entire generation.

We often assume waiting should lower our expectations. Sometimes it should. Age, health, and responsibility can require us to adjust wisely. Caleb’s example is not permission to deny our limits or force every season to look the same.

It asks a better question: Has delay made us release what no longer belongs to us, or abandon something we are still meant to do?

The hardest assignment is not always the bravest choice. Neither is the easiest. Courage means seeing the obstacles clearly, remembering why the work matters, and choosing the task that is actually ours.

Caleb did not ask for difficulty itself. He asked for the chance to finish faithfully.$pt$, $q$2026-06-21T16:00:00Z$q$, $q$publish$q$, 66, $q$https://stevesammons.com/give-me-the-hard-one/$q$, $q$https://sammons.substack.com/p/give-me-the-hard-one$q$, $q$https://sammons.substack.com/p/why-an-85-year-old-chose-giants$q$, $q$Why an 85-Year-Old Chose Giants$q$, null, $q$Caleb$q$, $q$done_before$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1852, $q$When Following Beats Leading$q$, $q$when-following-beats-leading$q$, $pt$BIG IDEA

The strongest move isn't always taking charge.

Sometimes winning means choosing who to follow.

We've been sold a myth that leaders never ask for help.

BACKGROUND

Around 1200 BC — about when Brad Pitt's Achilles was sacking Troy on the coast of modern Turkey, 700 miles north — a general named Barak commanded the army of Israel. His enemy fielded 900 iron chariots, the tanks of the ancient world. His story is in Judges 4-5. He's named in Hebrews 11:32 among history's heroes of faith.

STORY

A two-star general. Ten thousand troops. An enemy with iron chariots.

And he refused to march.

Not without Deborah, a prophetess who heard from God clearly. Barak could swing a sword. Deborah could hear the signal. He wanted both on the battlefield. (Judges 4:8)

The critics called it cowardice.

The critics were wrong.

We're told leadership means having all the answers. Being the smartest in the room. Needing no one.

Barak knew better. He also knew the cost. Deborah warned him the glory would go to a woman named Jael, who would finish the enemy commander with a tent peg. (Judges 4:9)

He took the deal anyway.

The mission mattered more than the credit.

The result? A storm flooded the river. The chariots bogged down in the mud. (Judges 5:21) The enemy was finished. The victory song was sung by two. (Judges 5:1)

Maybe leadership isn't about being strong enough to do it alone.

Maybe it's about being wise enough to know when not to.$pt$, $q$2026-06-14T16:00:00Z$q$, $q$publish$q$, 67, $q$https://stevesammons.com/when-following-beats-leading/$q$, $q$https://sammons.substack.com/p/when-following-beats-leading$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1818, $q$When Death Isn't the Hard Part$q$, $q$when-death-isnt-the-hard-part$q$, replace($pt$BIG IDEA

Sometimes getting what we asked for creates problems we never imagined.

The miracle is only the beginning.

What comes next requires a different kind of courage.

BACKGROUND

Lazarus lived in Bethany with his sisters, Mary and Martha. He was a close friend of Jesus. When Lazarus died, Jesus brought him back to life after four days in the tomb (John 11:1-44).

STORY

He walked out of his own grave.

Still wrapped in burial cloths.

Blinking against sunlight he never expected to see again.

Four days dead.

Then not.

That’s a miracle. No question.

But here’s what we often miss: the resurrection was not the end of the story.

It was the beginning of a new kind of danger.

Because now Lazarus had a target on his back.

John 12:10-11 tells us the chief priests made plans to kill him too. Not because he had done anything wrong. Not because he was leading a rebellion. But because his very existence had become inconvenient.

He was walking proof.

Proof of something they could not explain away.

Proof that Jesus had power they could not control.

Proof that the story was bigger than their authority.

Here’s what strikes me.

Lazarus didn’t choose to become a controversy.

He didn’t volunteer to be a symbol.

He was simply called out of death.

And that calling came with a cost.

Sound familiar?

Maybe you’ve experienced something like that.

A breakthrough that brought backlash.

A promotion that changed friendships.

A recovery that made some people uncomfortable.

A decision to tell the truth that made you unpopular.

Sometimes the thing that saves you also marks you.

And then you have to decide what to do with the life you’ve been given.

What’s remarkable is what Lazarus did next.

He showed up.

John 12:2 says he was at dinner with Jesus.

Sitting there.

Eating.

Being seen.

While people were already making plans against him.

He didn’t disappear.

He didn’t pretend the miracle had never happened.

He didn’t try to crawl back into something that looked like normal.

He lived.

Out loud.

There’s something here for us.

When we are called into new life, we cannot keep living as if we are still in the grave.

Some people won’t understand.

Some people won’t celebrate.

Some people may even prefer the old version of us, because the resurrected version tells the truth too clearly.

But we weren’t raised to hide.

Lazarus points us to a bigger story.

Soon, his friend Jesus would face death too.

And then another tomb would be empty.

Matthew 28:6 says, “He is not here[[semicolon]] he has risen.”

The one who called Lazarus out of death would conquer death completely.

That’s the pattern.

Called from death.

Given new life.

Invited into courage.

Trusting that the one who raised us knows exactly what comes next.

The grave was never meant to be permanent.

Neither is our fear.$pt$, '[[semicolon]]', chr(59)), $q$2026-06-07T21:00:00Z$q$, $q$publish$q$, 68, $q$https://stevesammons.com/when-death-isnt-the-hard-part/$q$, $q$https://sammons.substack.com/p/when-death-isnt-the-hard-part$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1848, $q$When Skill Isn't Enough$q$, $q$when-skill-isnt-enough$q$, $pt$BIG IDEA

We celebrate talent. We admire skill. But we keep missing something.

One of Scripture’s most remarkable craftsmen knew it. Expertise alone doesn't create what matters most.

BACKGROUND

Bezalel (BEZ-a-lell) was the lead artist on history's most ambitious sacred project. God called Bezalel by name to design and build the Tabernacle. His job was to create beauty that could hold the presence of God.

STORY

The materials were extraordinary. Gold. Silver. Bronze. Precious stones.

The client was God himself.

And yet, before Bezalel picked up a single tool, something had to happen first.

Here’s what’s interesting.

God didn’t merely say, “I have found a skilled craftsman.”

He said, “I have filled him with my Spirit” (Exodus 31:3).

Not credentials first. Not portfolio first. Not years of experience first.

The Spirit was the source of wisdom, understanding, knowledge, and craftsmanship.

How many times do we get the order backward?

We grind. We hustle. We master the craft. Then, maybe, we pause to ask for help.

Bezalel couldn’t afford that sequence. His assignment was too important.

What if the filling comes before the doing?

What if the source matters more than the skill?

But here’s the cool part. Bezalel is the first person in Scripture explicitly described as being filled with God’s Spirit. Not for preaching. Not for prophecy. Not for standing behind a pulpit.

For art. For metalwork. For design.

God filled a craftsman.

Bezalel did not work alone. God also gave Bezalel and Oholiab (oh-HO-lee-ab) the ability to teach others, multiplying the work through a team of artisans.

It’s like a math equation.

Skill without filling creates impressive work.

Filling without skill creates sincere attempts.

But skill plus filling? That’s when craft becomes calling.

Maybe we don’t need more technique.

Maybe we need a better source.

How the image was created.$pt$, $q$2026-05-31T16:00:00Z$q$, $q$publish$q$, 69, $q$https://stevesammons.com/when-skill-isnt-enough/$q$, $q$https://sammons.substack.com/p/when-skill-isnt-enough$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1846, $q$Stop Calling It Humility$q$, $q$stop-calling-it-humility$q$, replace($pt$Gideon is hiding in a winepress, threshing wheat. Scared. Small. Hidden from the enemy.

That's where the angel of the Lord finds him.

The angel's first words: "The Lord is with you, mighty warrior" (Judges 6:12).

Mighty warrior. While he's hiding.

Gideon's response is the response of every man caught in false humility: "I am the least in my family, and my family is the weakest in the tribe" (Judges 6:15).

God doesn't argue. He just keeps calling Gideon what he already is.

The Verse We Don't Quote in Full

When Jesus was asked to name the greatest commandment, he gave two.

"Love the Lord your God with all your heart, soul, mind, and strength. And love your neighbor as yourself" (Mark 12:30-31).

We talk about loving God. We talk about loving our neighbor.

We rarely talk about the last two words.

Read it again: Love your neighbor as yourself.

Jesus didn't say instead of yourself. He didn't say more than yourself. He said as yourself — and then he walked away, assuming you knew how to do that.

You can't pour love out of an empty cup. You can't believe God shaped someone else with intention and believe he forgot what he was doing when he got to you.

If you don't see yourself the way he does, you'll never love your neighbor the way he does either.

The Quiet Trick

I've watched a young man I love do this.

Someone tells him he'd be great at something. He waves it off.

Someone sees a gift in him he hasn't named yet. He shrinks.

You've probably watched someone do this. Maybe you've done it yourself.

It looks like humility. It isn't.

False humility wears the costume of virtue. It deflects compliments. It dismisses gifts. It calls itself modest. But the person deflecting isn't thinking less of themselves. They're thinking about themselves more than anyone else in the room.

Often, the deflection is a quiet bid. "Oh, I don't know about that" is sometimes a request — for someone to push back, to reassure, to say it again with more conviction. That's not humility. That's a handout, asking for approval.

Rick Warren put it cleanly in The Purpose Driven Life:

"Humility is not thinking less of yourself[[semicolon]] it is thinking of yourself less."

Real humility doesn't show up at the conversation about you. It's already out the door, looking for someone to serve.

False humility is just self-focus in a holier outfit.

What It Costs You

Here's where this gets practical.

A person stuck in false humility will never set a goal that scares them. They'll never write down the thing God put in their chest. They'll never say it out loud.

Because saying it out loud feels like bragging.

So they shrink. They aim low. They call it modesty.

And the gift sits in the corner, unwrapped.

My dad had a question he would ask anyone stuck in this:

What would you do if you knew you couldn't fail?

Sit with it. Don't answer fast.

The size of your dream is downstream of how you see yourself. Answer the question honestly, and you'll find out what you actually believe about who God made you to be.

Six Books Worth Your Time

If this is hitting something in you, keep going. Here's where I'd send you. I have written up some short reviews for each of these books, in case you just want to get a taste.

Rick Warren — The Purpose Driven Life. The book that put the "thinking of yourself less" reframe into the bloodstream of modern Christianity. Forty days. Worth every one.

Joyce Meyer — Battlefield of the Mind. Thirty years in print. Nearly eight million copies sold. It is about what you let your mind say to you — and how to put a stop to it.

Mark Batterson — Chase the Lion. Built around the story of Benaiah, who in 2 Samuel chased a lion into a pit on a snowy day and killed it. Batterson's whole point: stop running from the lion. Chase it. The book is a permission slip to set goals so big they need God to pull off.

John Maxwell — The 15 Invaluable Laws of Growth. Pastor turned leadership teacher. Sells in churches and corner offices. The Law of Awareness alone reads like a diagnostic for false humility.

Carol Dweck — Mindset. A Stanford psychologist on why some people believe they can develop and others believe they're stuck. The science underneath everything above.

Steven Pressfield — The War of Art. Names the enemy. Pressfield calls it Resistance — the force inside you that whispers "not yet, not you, not today" every time you sit down to do the work God put in you. Short book. Hits like a hammer. Not written from a Christian frame, but reads like it half the time.

Read them with a pen.

The Charge

If you've been deflecting compliments and calling it humility — stop.

You are not loving anyone better by undervaluing what God put in you.

Write down the goal you'd write down if you knew you couldn't fail.

Then go work on it.

Love your neighbor.

Love your neighbor as yourself.

The whole verse.

How the Gideon image was created.$pt$, '[[semicolon]]', chr(59)), $q$2026-05-24T16:00:00Z$q$, $q$publish$q$, 70, $q$https://stevesammons.com/stop-calling-it-humility/$q$, $q$https://sammons.substack.com/p/stop-calling-it-humility$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1826, $q$When Your Greatest Strength Becomes Dangerous$q$, $q$when-your-greatest-strength-becomes-dangerous$q$, $pt$BIG IDEA

The thing we're best at can become the thing that blinds us most.

Sometimes our greatest asset needs to be dismantled before we can truly lead.

BACKGROUND

Paul was a religious prodigy. Top of his class. Connected to power. He had every credential a leader could want. Then everything changed on a dusty road—and with it, our understanding of what real transformation requires.

STORY

He was hunting people.

Letters of authority in his bag. Chains ready for arrests. Saul—the man who would become Paul—traveled toward Damascus with murder on his mind (Acts 9:1-2).

This wasn't some conflicted soul searching for meaning.

He was certain. Absolutely certain.

And that's what made him dangerous.

Here's what we're discovering together: Certainty without humility is a weapon. The more competent we become, the more careful we need to be.

Paul had the resume. He later listed his credentials: perfect pedigree, elite education, flawless religious record (Philippians 3:4-6). By every measure, he was winning.

But winning at what?

The light knocked him down. The voice asked one question: "Why are you persecuting me?" (Acts 9:4).

Not: Why are you wrong?

Not: Why are you evil?

Just: Why are you fighting against what you claim to serve?

That question changes everything.

Paul spent three days blind. Think about that. The man who saw everything so clearly couldn't see at all. He had to depend on others. He had to wait. He had to let go.

This is the pattern we keep finding in great leaders: Before they build, something has to break.

Years later, Paul wrote something stunning. All those credentials? He called them garbage (Philippians 3:8). Not because they were false. They were true. They just weren't the point.

The persecutor became the apostle. The hunter became the hunted. The man who destroyed communities spent his life building them.

At the end, chained in a Roman prison, he wrote: "I have finished the race" (2 Timothy 4:7).

Not the race he started. A completely different one.

Maybe the question isn't whether we're running hard enough. Maybe it's whether we're running in the right direction. And whether we're humble enough to change course when we discover we're not.$pt$, $q$2026-05-17T16:00:00Z$q$, $q$publish$q$, 71, $q$https://stevesammons.com/when-your-greatest-strength-becomes-dangerous/$q$, $q$https://sammons.substack.com/p/when-your-greatest-strength-becomes-dangerous$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1850, $q$When No One Else Will Move$q$, $q$when-no-one-else-will-move$q$, $pt$BIG IDEA

The best leaders often never planned to lead. They simply stepped forward when everyone else stepped back.

BACKGROUND

Deborah lived around 1200 BC during Israel's darkest chapter. She held three titles at once: judge, prophet (Judges 4:4-5), and mother (Judges 5:7). In a world run by men, she became the one person everyone trusted to settle disputes and speak truth.

STORY

The general refused to go to war without her.

Think about that.

Barak had 10,000 soldiers. He had the strategy. He had the divine command to march. But he told Deborah, "If you don't go with me, I won't go" (Judges 4:8).

This wasn't weakness. It was recognition.

He knew something we often miss: titles don't create trust. Presence does.

Deborah sat under a palm tree between Ramah and Bethel. People climbed the hill to find her. Not because of her office. Because of her clarity.

She didn't campaign for the job. She just kept showing up. Kept listening. Kept telling the truth when silence would have been easier.

Here's what's uncomfortable for us.

Sometimes we're waiting for permission that nobody's going to give. We're hoping someone more qualified will step forward. Someone with better credentials. More experience. A louder voice.

Deborah wasn't waiting.

When the battle came, she marched to Mount Tabor with an army she didn't command. She spoke the word that sent them charging down the slope. And the enemy scattered (Judges 4:14-15).

Her song after the victory tells us something crucial. She called herself "a mother in Israel" (Judges 5:7). Not a warrior. Not a commander. A mother.

We keep looking for the perfect leader.

Maybe the real question is simpler: Who's willing to go first?$pt$, $q$2026-05-10T21:00:00Z$q$, $q$publish$q$, 72, $q$https://stevesammons.com/when-no-one-else-will-move/$q$, $q$https://sammons.substack.com/p/when-no-one-else-will-move$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1856, $q$When Stepping Back Is Stepping Up$q$, $q$when-stepping-back-is-stepping-up$q$, $pt$By Steve Sammons

BIG IDEA

Sometimes the bravest thing we can do is clear the path for someone else.

The world celebrates people who fight for what's theirs. But what if real strength looks like handing over what was promised to you?

BACKGROUND

Jonathan was next in line for the throne of Israel. His father was King Saul, and the crown was his birthright. But Jonathan recognized something most of us miss: destiny doesn't always follow bloodlines. Sometimes it follows calling.

STORY

Here's a prince who wins a battle with just his armor-bearer.

Just two men. Climbing a cliff. Defeating twenty enemy soldiers. Triggering an earthquake and a full-scale rout (1 Samuel 14:1-23).

This guy was no pushover.

And yet.

When David walked into his life—a shepherd boy who'd just taken down a giant—Jonathan didn't see a rival. He saw a friend. He saw a future king.

So Jonathan did something unthinkable.

He took off his royal robe and gave it to David. Then his armor. Then his sword, bow, and belt (1 Samuel 18:3-4).

Every symbol of his future power. Handed over. Freely.

We're trained to climb. To compete. To protect what's ours.

Jonathan shows us another way.

When his father tried to kill David, Jonathan warned him. When Saul's jealousy turned murderous, Jonathan protected the very man who would take his throne (1 Samuel 19-20).

This was wisdom vs. weakness.

Years later, when David was hiding in the wilderness, exhausted and hunted, Jonathan found him. He didn't come to reclaim anything. He came to encourage. "Don't be afraid," he said. "You will be king over Israel, and I will be second to you" (1 Samuel 23:16-17).

Second.

A crown prince. Choosing second place. On purpose.

Most of us spend our lives trying to be first. The Jonathan story illustrates that knowing when to be second might be the greater gift.

He never got to serve alongside David. He died in battle with his father (1 Samuel 31). David's lament for him is one of the most beautiful passages in Scripture: "Your love to me was extraordinary, surpassing the love of women" (2 Samuel 1:26).

Jonathan pointed beyond himself—to a better king, a greater kingdom.

Centuries later, another man would say: "He must increase, but I must decrease" (John 3:30).

Same posture. Same humility. The same recognition that some things matter more than our own advancement.

What if the best leadership move we could make isn't grabbing more?

What if it's opening our hands?$pt$, $q$2026-05-03T21:00:00Z$q$, $q$publish$q$, 73, $q$https://stevesammons.com/when-stepping-back-is-stepping-up/$q$, $q$https://sammons.substack.com/p/when-stepping-back-is-stepping-up$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1783, $q$The Disqualification You Need$q$, $q$the-disqualification-you-need$q$, $pt$BIG IDEA

The best leaders don't start by seeing their potential. They start by seeing their problem.

We think confidence launches us forward. But maybe it's the opposite.

BACKGROUND

Isaiah was an advisor to kings. He moved in royal circles for decades. He spoke truth to power when it cost him everything. His writings shaped Western civilization.

But his career didn't start with ambition. It started with terror.

STORY

He was in the temple when the room started shaking.

Smoke. Creatures with six wings. A voice that rattled the doorposts.

And Isaiah's first response wasn't excitement. Wasn't ambition. Wasn't "pick me."

It was this: "Woe is me! I am ruined!" (Isaiah 6:5).

Here's what's strange.

Isaiah wasn't a criminal. He was already respected. Already doing good work.

But in that moment, he saw the gap.

The gap between who he thought he was and what the job actually required.

We skip this part.

We build confidence exercises. We rehearse our strengths. We highlight our wins.

Isaiah did something different.

He called himself "a man of unclean lips" living among "a people of unclean lips" (Isaiah 6:5). His problem wasn't just personal. It was shared. He was part of the system he needed to address.

This is where it gets interesting.

Only after the admission came the commission.

A burning coal. Touched to his lips. "Your guilt is taken away" (Isaiah 6:7).

Then—and only then—came the question: "Whom shall I send?" (Isaiah 6:8).

Isaiah spent the next sixty years delivering messages most people didn't want to hear. He wrote about a coming servant who would be "pierced for our transgressions" (Isaiah 53:5)—words that echo through history.

John later wrote that Isaiah "saw Jesus' glory and spoke about him" (John 12:41).

But it all started with a man on the floor. Undone. Exposed.

Maybe the disqualification we fear is actually the qualification we need.

Seeing our own uncleanness isn't weakness. It's the first honest moment.

And honest is where real leadership begins.$pt$, $q$2026-04-26T21:00:00Z$q$, $q$publish$q$, 74, $q$https://stevesammons.com/the-disqualification-you-need/$q$, $q$https://sammons.substack.com/p/the-disqualification-you-need$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1822, $q$When Dead Men Still Deliver$q$, $q$when-dead-men-still-deliver$q$, $pt$BIG IDEA

What if our greatest contribution happens after we're gone?

Most of us measure impact by what we accomplish while we're in the room. But maybe we've been measuring the wrong thing.

BACKGROUND

Elisha was a farmer who became a prophet in ancient Israel around 850 BC. He succeeded Elijah, one of the most famous leaders of his era. His story spans twenty-five chapters and sixty years of influence (2 Kings 2-13).

STORY

A dead body falls into a grave.

The corpse touches some old bones at the bottom. And then—the impossible—the dead man stands up, alive (2 Kings 13:21).

Those bones belonged to Elisha. He'd been dead for years.

Still delivering.

Here's what we don't talk about enough: Elisha asked for this.

When his mentor Elijah was about to leave, Elisha made a bold request. "Let me inherit a double portion of your spirit" (2 Kings 2:9).

Not equal. Double.

We often hesitate to ask for more than our predecessors had. It feels presumptuous. Disrespectful, even.

But Elisha understood something we forget.

Good mentors don't want you to repeat their work. They want you to exceed it.

Elijah performed seven miracles. Elisha performed fourteen. Double.

He healed poisoned water. Fed a hundred men with twenty loaves. Cured a foreign general named Naaman when no one else in Israel was healed—a point Jesus himself would later emphasize (Luke 4:27).

But the bones. Those bones in the grave.

That's the part that haunts me.

Because it suggests that what we build can keep working after we stop. That legacy isn't about what people say at our funeral. It's about what still happens because of how we lived.

The systems we create. The people we develop. The culture we shape.

These keep delivering when we can't.

Most succession planning focuses on the wrong question. We ask, "Who will replace me?"

Maybe we should ask, "What am I building that doesn't need me?"

Elisha poured himself into prophetic communities. He trained leaders. He invested in institutions that would outlast his influence.

Even centuries later, his life pointed forward. The resurrection power in those bones whispered of a greater resurrection to come—when another prophet would walk out of his own grave, this time permanently.

So here's the question for today:

Are we building something that dies with us, or something that delivers after we're gone?$pt$, $q$2026-04-19T21:00:00Z$q$, $q$publish$q$, 75, $q$https://stevesammons.com/when-dead-men-still-deliver/$q$, $q$https://sammons.substack.com/p/when-dead-men-still-deliver$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1820, $q$When Miracles Aren't Enough$q$, $q$when-miracles-arent-enough$q$, $pt$Big Idea

Peak performance has a ceiling. The same leader who commands the impossible can still fall apart. We're not built for unending victory—and pretending otherwise will break us.

Background

Elijah was an ancient prophet who stood alone against a corrupt kingdom. He challenged kings, predicted drought, and raised the dead. His story spans 1 Kings 17-19 and 2 Kings 2—a leadership arc that reaches impossible heights before crashing to devastating lows.

Story

Imagine commanding fire to fall from the sky.

Then, forty-eight hours later, begging to die.

That's Elijah's story. And maybe ours too.

On Mount Carmel, Elijah faced 850 false prophets. He mocked them. He drenched his altar with water. Then fire fell from heaven and consumed everything—stones, dust, water (1 Kings 18:38).

The crowd fell on their faces. The enemy scattered.

Total victory.

And then?

One threat from Queen Jezebel, and Elijah ran. Not walked—ran. Into the wilderness. Alone. Collapsed under a tree and asked God to end his life (1 Kings 19:4).

Think about this...we might have missed it in his burnout:

It doesn't come from failure. It comes from success.

The very thing that made Elijah powerful—his intensity, his willingness to stand alone—was the same thing that emptied him.

God didn't lecture him. Didn't quote Scripture. He sent an angel with bread and water (1 Kings 19:5-6). Then he sent him to sleep.

Twice.

The prophet who called fire from heaven needed a nap and a snack.

There's something almost embarrassing about that. We want our heroes to transcend human limits. We want to transcend them ourselves.

But Elijah's story tells us something different.

Centuries later, Jesus took Peter, James, and John up a mountain. Moses appeared. So did Elijah—talking with Jesus about what was coming (Luke 9:28-31). The prophet who wanted to die now stood in glory, helping to usher in something greater.

Malachi prophesied that Elijah would return before the great day (Malachi 4:5-6). That promise pointed forward to John the Baptist, preparing the way.

Elijah's lowest moment didn't disqualify him. It prepared him.

My dad had a saying: "Are you as open to God's truth today as you were the day you first found it?"

Maybe the crash after the conquest isn't a bug in the system.

Maybe it's the doorway to something we can't reach any other way.$pt$, $q$2026-04-12T21:00:00Z$q$, $q$publish$q$, 76, $q$https://stevesammons.com/when-miracles-arent-enough/$q$, $q$https://sammons.substack.com/p/when-miracles-arent-enough$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1824, $q$The Strongest Leaders Fail First$q$, $q$the-strongest-leaders-fail-first$q$, $pt$BIG IDEA

The person who becomes the foundation isn't the one who never fell.

It's the one who fell hardest—and got back up.

Maybe we've been measuring leadership potential all wrong.

BACKGROUND

Peter was a fisherman. Loud. Impulsive. The first to speak and often the first to regret it.

Jesus chose him anyway. Called him "the rock." Then watched him crumble.

STORY

Three times.

That's how many times Peter denied knowing Jesus. In one night. Around a fire. While Jesus was being led to his death (Matthew 26:69-75).

Not a small stumble. A total collapse.

Here's what's strange.

Jesus had already named him. "You are Peter, and on this rock I will build my church" (Matthew 16:18).

The rock. The foundation.

And then the rock crumbled into dust.

We'd fire that guy. Or at least demote him.

Not Jesus.

After the resurrection, Jesus finds Peter by another fire. Three questions this time. "Do you love me?" Three chances to rebuild what was broken (John 21:15-17).

Here's what we often miss:

Peter's failure didn't disqualify him.

It prepared him.

The guy who denied Jesus three times? He preached the first sermon of the early church. Three thousand people responded (Acts 2:41).

The man who ran from a servant girl's question became the leader who faced rulers and refused to back down.

Something shifted.

Peter stopped pretending he had it all together.

That's when he became unshakeable.

We keep looking for leaders who've never fallen.

But maybe the strongest foundations are built by people who know what it's like to break.

They lead differently. With humility. With grace for others who stumble.

Peter's story whispers something we need to hear:

Your worst moment doesn't have to be the final word.

Sometimes it's the first word of a better story.$pt$, $q$2026-04-05T21:00:00Z$q$, $q$publish$q$, 77, $q$https://stevesammons.com/the-strongest-leaders-fail-first/$q$, $q$https://sammons.substack.com/p/the-strongest-leaders-fail-first$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1808, $q$When Trust Requires Everything$q$, $q$when-trust-requires-everything$q$, $pt$BIG IDEA

The hardest test of trust isn't believing. It's walking forward when you can see the fire but not the ram.

Sometimes we're called to carry what we don't fully understand.

BACKGROUND

Isaac was the long-awaited son of Abraham and Sarah. He was the promise fulfilled—the child who wasn't supposed to exist. His story in Genesis isn't flashy. He didn't part seas or slay giants. But he carried something heavier: the weight of being the sacrifice before he became the survivor.

STORY

Here's what stops me cold about Genesis 22.

Isaac carried the wood.

His father carried the fire and the knife. But the wood for the burnt offering? That was on Isaac's back.

He wasn't a small child. Scholars suggest he was likely a young man—strong enough to carry firewood up a mountain. Strong enough to resist if he'd chosen to.

He asked the question: "Father, I see the fire and the wood. But where is the lamb for the offering?" (Genesis 22:7)

Abraham's answer was both honest and incomplete: "God will provide the lamb, my son."

And Isaac kept walking.

That's the part we rush past.

He didn't have the full picture. He sensed something was off. But he trusted enough to keep moving.

Hebrews 11:17-19 tells us Abraham believed God could raise the dead. But Isaac? He had to trust his father. He had to believe that even when the situation didn't add up, the relationship was worth following.

This is where leadership gets uncomfortable for all of us.

We want vision. We want clarity. We want the full briefing before we commit.

Isaac teaches us something different.

Sometimes you carry the weight before you understand the purpose.

Later in Genesis 26, Isaac faced his own tests. He re-dug the wells his father had dug. He dealt with conflict and scarcity. He made mistakes—like his father, he lied about his wife out of fear.

He wasn't perfect.

But here's what Isaac did right: he stayed in the story.

He didn't run from the altar. He didn't abandon the wells. He inherited a promise and passed it forward—not perfectly, but faithfully.

Centuries later, another Son would carry wood up a hill.

That one didn't receive a substitute. He became it.

Isaac's story whispers what the cross shouts: trust sometimes looks like surrender.

The weight we carry today might be the very thing that's preparing us for what we can't yet see.$pt$, $q$2026-03-29T16:00:00Z$q$, $q$publish$q$, 78, $q$https://stevesammons.com/when-trust-requires-everything/$q$, $q$https://sammons.substack.com/p/when-trust-requires-everything$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1815, $q$Why Skeptics Make the Best Believers$q$, $q$why-skeptics-make-the-best-believers$q$, $pt$BIG IDEA

The people who ask hard questions aren't the problem. They're the solution.

Doubt isn't the opposite of belief. It's the pathway to something deeper.

BACKGROUND

Thomas was one of Jesus' twelve closest followers. History nicknamed him "Doubting Thomas." But that label misses the point entirely. He was the one brave enough to say what everyone else was thinking.

STORY

Here's what nobody tells you about Thomas.

He wasn't a coward.

When Jesus decided to walk straight into danger, Thomas spoke up. "Let us also go, that we may die with him" (John 11:16). That's not doubt. That's loyalty.

When the other disciples were confused about where Jesus was going, Thomas asked the question. "Lord, we don't know where you are going. How can we know the way?" (John 14:5).

That question gave us one of the most famous answers in history.

Here's what we need to understand.

Thomas wasn't there when Jesus first appeared to the disciples after the resurrection. He missed the moment. And when they told him what happened, he refused to believe it.

"Unless I see the nail marks... I will not believe" (John 20:25).

We call that doubt.

But maybe it's something else.

Maybe Thomas knew that belief without evidence is just wishful thinking. Maybe he understood that what we accept without question, we hold loosely.

A week later, Jesus came back. He looked at Thomas. "Put your finger here... Stop doubting and believe" (John 20:27).

And Thomas gave the greatest declaration of faith in the entire Bible.

"My Lord and my God" (John 20:28).

No one else said that. Not Peter. Not John. Not anyone.

The skeptic became the worshiper.

This is the pattern. The people who wrestle with truth don't walk away from it. They walk into it. Their questions forge something unshakeable.

We need more people like Thomas on our teams. The ones who ask "are we sure?" before we jump. The ones who want to see the evidence.

Because when they finally believe, they believe with everything.

Doubt isn't your enemy. It's the doorway.$pt$, $q$2026-03-29T21:00:00Z$q$, $q$publish$q$, 79, $q$https://stevesammons.com/why-skeptics-make-the-best-believers/$q$, $q$https://sammons.substack.com/p/why-skeptics-make-the-best-believers$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1810, $q$When Certainty Becomes the Trap$q$, $q$when-certainty-becomes-the-trap$q$, replace($pt$BIG IDEA

The moment we become convinced we see more clearly than everyone else, we've already started walking toward disaster. Certainty feels like strength. But sometimes it's just a shortcut past the wisdom we weren't patient enough to receive.

BACKGROUND

Judas Iscariot was one of twelve hand-picked leaders in history's most influential inner circle. He managed the money. He had a seat at the table. And yet, he became synonymous with betrayal—not because he was an outsider, but precisely because he was so close.

STORY

Thirty pieces of silver.

That's the price of a slave. It's also what Judas accepted to betray his friend (Matthew 26:15).

Here's what's strange.

Judas wasn't the obvious villain. He wasn't lurking in shadows. He was trusted. He carried the money bag (John 13:29). He had access.

And that's exactly where things went wrong.

We don't know exactly what Judas expected. Some scholars think he was trying to force a confrontation—push Jesus into finally claiming political power. Others think he simply lost faith in the mission.

What we do know: he thought he knew better.

The timeline matters here.

At the last supper, Jesus dips bread and hands it directly to Judas. A gesture of honor. A final invitation (John 13:26-27).

Judas takes it and leaves.

Later, in the garden, Judas greets Jesus with a kiss. The signal to the soldiers. Even the betrayal is wrapped in intimacy (Matthew 26:49).

And then comes the part we rarely talk about.

When Judas sees what happens next—the arrest, the sham trial, the march toward crucifixion—something shifts. He returns the money. He confesses: "I have betrayed innocent blood" (Matthew 27:4).

The religious leaders shrug. "What is that to us?"

Remorse without repair is its own kind of trap.

Here's what sticks out to me.

Proximity doesn't equal alignment. Judas was close to Jesus physically. But his heart drifted toward a different agenda.

We do this too.

We sit in the meetings. We nod at the mission statement. And somewhere along the way, we start running a parallel operation in our minds—convinced our version is smarter, more practical, more realistic.

The danger isn't disagreement. Healthy teams disagree.

The danger is secret certainty. The private conviction that we see what others miss.

That kind of certainty doesn't ask questions. It stops listening. And eventually, it acts alone.

Jesus, interestingly, never stopped offering connection. The bread. The naming. Even the greeting in the garden: "Friend, do what you came to do" (Matthew 26:50).

The door stayed open.

Judas just never walked back through it.

The question for me isn't whether I am capable of betrayal[[semicolon]] I am.

It's whether I can be humble enough to recognize when I've started believing my own version of the story—and courageous enough to return before certainty leads me into the night.$pt$, '[[semicolon]]', chr(59)), $q$2026-03-22T16:00:00Z$q$, $q$publish$q$, 80, $q$https://stevesammons.com/when-certainty-becomes-the-trap/$q$, $q$https://sammons.substack.com/p/when-certainty-becomes-the-trap$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
