-- Generated by songs/supabase/export_posts.py. Run in Supabase > SQL Editor after schema.sql.
-- 52 scheduled and 46 published Bible-character posts.

-- Part 5 of 5.

insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1798, $q$When Pressure Makes You Improvise$q$, $q$when-pressure-makes-you-improvise$q$, $pt$BIG IDEA

Under pressure, we build what people want. Not what they need.

That's the easier path. And it's almost always the wrong one.

BACKGROUND

Aaron was Moses's older brother. He spoke for Moses when Moses couldn't find the words. He became Israel's first high priest. But we remember him for something else entirely.

STORY

Here's the moment that changed everything.

Moses climbs a mountain. He's gone forty days.

The people get nervous. Then anxious. Then demanding.

"Make us gods," they tell Aaron. "Moses isn't coming back" (Exodus 32:1).

Aaron doesn't push back. He doesn't call them to patience.

He collects their gold earrings. He builds exactly what they asked for—a golden calf (Exodus 32:2-4).

He even builds an altar and declares a festival to the Lord (Exodus 32:5).

Here's what's fascinating.

Aaron knew better. He'd seen the plagues in Egypt. He'd watched the Red Sea split. He'd eaten manna from heaven.

He had all the information he needed.

But information doesn't create courage.

When the crowd got loud, Aaron got compliant. He gave them a god they could control. Not the God they couldn't.

This is the leadership trap we rarely discuss.

It's not that we don't know what's right. It's that knowing isn't the same as doing—especially when everyone around us pushes the other direction.

Aaron's excuse is telling: "They gave me the gold, I threw it in the fire, and out came this calf" (Exodus 32:24).

As if it just happened. As if he had no choice.

We do this too, don't we? We blame circumstances. The team. The timeline. The budget.

I know this feeling.

These situations keep coming. Someone creating friction. Missing the mark. Pulling the team sideways.

I see it. I know it.

But the timing is never right. The stakes are too high. The relationships too complicated. So I work around it instead of through it.

I tell myself I'm being patient.

I'm not. I'm just collecting gold.

And when it finally collapses, I have a hundred reasons why it just happened that way.

But here's what Aaron discovered later.

He still became Israel's high priest. He still wore the sacred garments described in Exodus 28. He still stood between God and people on the Day of Atonement (Leviticus 16).

Failure wasn't final.

The same hands that shaped the golden calf later offered sacrifices. Those sacrifices pointed forward—to someone greater who would come as the ultimate High Priest (Hebrews 5:1-4).

What changed?

Aaron was given another chance.

Leadership isn't about having all the answers. It's about having the courage to wait for the right ones.

Even when everyone else is collecting gold.$pt$, $q$2026-03-15T16:00:00Z$q$, $q$publish$q$, 81, $q$https://stevesammons.com/when-pressure-makes-you-improvise/$q$, $q$https://sammons.substack.com/p/when-pressure-makes-you-improvise$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1796, $q$When Running Makes It Worse$q$, $q$when-running-makes-it-worse$q$, $pt$BIG IDEA

Sometimes we run from the very thing that would set us free.

We avoid the hard conversation. We dodge the assignment. We resist the mercy that could heal us.

Not because we don’t understand it.

Because we do.

The truth is, running rarely solves anything. It just relocates the problem.

BACKGROUND

Jonah was a prophet in ancient Israel around 780 BC. His job was to say what God said, even when it hurts.

What makes his story remarkable isn’t that he ran from danger.

He ran from mercy.

More specifically, he ran from the possibility that God might show mercy to people Jonah hated (Jonah 1:1-3).

That changes the whole story.

STORY

Here’s a man who got exactly what he wanted—and hated the outcome.

God told Jonah to go to Nineveh.

Nineveh was the enemy. Violent. Oppressive. The kind of place people wanted judged, not forgiven.

So Jonah went the other way (Jonah 1:3).

We know what happened next. Storm. Ship. Sailors terrified. Jonah overboard. Big fish...really big fish.

Three days in the dark (Jonah 1:17).

Eventually, Jonah obeyed. He went to Nineveh. He preached the warning. And the city repented (Jonah 3:5-10).

The mission worked.

And Jonah was furious.

“I knew it,” he told God. “I knew that you are gracious and compassionate, slow to anger and abounding in love” (Jonah 4:2).

Don’t miss this.

Jonah did not run because God was too harsh.

He ran because God was too merciful.

He knew exactly who God was.

He just did not want God to be that way for them.

That is what makes Jonah so exposing.

He wanted grace for himself and judgment for his enemies.

And if we are honest, so do we.

Jonah sat outside the city, hoping God might still destroy it (Jonah 4:5).

Then God gave him a plant for shade. Jonah loved the plant.

God took the plant away. Jonah wanted to die (Jonah 4:6-8).

A prophet more upset about losing a plant than losing a city.

More troubled by discomfort than by 120,000 human beings.

Then God asked the question that ends the book: You care about a plant you did nothing to grow. Shouldn’t I care about 120,000 people in Nineveh? (Jonah 4:10-11, paraphrased)

And that is where the story stops.

No resolution. No cleanup. Just a question hanging in the air.

Because the point is not Jonah’s answer.

It is ours.

Leadership is not just about doing the assignment.

It is about letting God deal with your heart as you do.

Jonah obeyed. But obedience alone did not make him surrender.

He delivered the message while resenting the mercy behind it.

That is the danger.

We can do the right thing with the wrong spirit.

We can say what is true and still be angry when grace lands on people we do not think deserve it.

The real question is not whether we will obey.

The real question is whether we can rejoice when God is kinder than we wanted Him to be.

Especially toward them.$pt$, $q$2026-03-09T10:04:15Z$q$, $q$publish$q$, 82, $q$https://stevesammons.com/when-running-makes-it-worse/$q$, $q$https://sammons.substack.com/p/when-running-makes-it-worse$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (2064, $q$The Decision That Outlives You$q$, $q$the-decision-that-outlives-you$q$, $pt$BIG IDEA

Some decisions don’t just affect today.

They shape generations.

And the most dangerous ones rarely feel dramatic in the moment.

BACKGROUND

In Genesis 3, Adam stands in a garden with a single boundary.

One tree.
One command.
One choice.

Don’t eat from it.

That’s it.

No complexity. No ambiguity.

Just trust.

Thousands of years later, a different kind of garden exists—server rooms, labs, code repositories.

A few people sit at tables making decisions about artificial intelligence that will influence economies, culture, and even what it means to be human.

Recently, Dario Amodei, CEO of Anthropic, spoke with Ross Douthat on the podcast Interesting Times with Ross Douthat about the future of AI and the responsibility that comes with building it: "We Don’t Know if the Models Are Conscious."

A handful of leaders.
Global consequences.

STORY

Adam’s decision probably didn’t feel historic.

It felt small.

Immediate.

Reasonable.

The fruit looked good. The argument made sense. The moment passed quickly.

And then everything changed.

Exile.
Toil.
Death.

Not because the fruit was powerful.

Because decisions compound.

We like to believe the choices that reshape the world feel heavy while we’re making them.

They usually don’t.

They feel efficient.
Innovative.
Necessary.

A product ships.
A feature launches.
A shortcut saves time.
A compromise smooths tension.

And only later do we discover what we actually voted for.

Here’s what strikes me.

Adam couldn’t see the generations attached to his bite.

AI founders can’t see every unintended consequence attached to their code.

And I can’t see the full impact of the small decisions I justify every day.

But that doesn’t mean the impact isn’t real.

Every decision is a seed.

Some grow into shade.
Some grow into thorns.

The real question isn’t whether our decisions matter.

It’s whether we’re thinking far enough ahead to care.

Because most of us won’t lead a tech company.

But all of us are shaping something.

A family.
A team.
A church.
A reputation.
A soul.

Adam teaches us something uncomfortable.

You don’t need many decisions to alter the future.

Sometimes you just need one.

Here’s what I’m wrestling with:

Am I choosing only for today?

Or am I choosing with the weight of tomorrow in mind?

Because once the fruit is bitten—

You don’t get the garden back.$pt$, $q$2026-03-01T16:14:00Z$q$, $q$publish$q$, 83, $q$https://stevesammons.com/the-decision-that-outlives-you/$q$, $q$https://sammons.substack.com/p/the-decision-that-outlives-you$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1790, $q$When Nobody Wants to Hear It$q$, $q$when-nobody-wants-to-hear-it$q$, $pt$BIG IDEA

Some messages are too important to stop delivering. Even when no one listens. Especially when no one listens.

BACKGROUND

Jeremiah was an ancient prophet who spoke to a nation heading toward disaster. For forty years, he warned them. For forty years, they refused to listen. His story sits in the Old Testament book that bears his name.

STORY

He got thrown into a muddy pit for telling the truth.

Not once. Not twice. Multiple times, the powerful people tried to silence him. They threw him in prison. They dropped him into a cistern to die. They burned his writings.

And he kept speaking anyway.

Here's what strikes me about Jeremiah. God told him upfront: "They will not listen to you" (Jeremiah 7:27). Imagine that job interview. "You'll work for forty years. Zero conversions. Ready to sign?"

He signed.

We tend to measure leaders by results. Followers gained. Revenue increased. Metrics achieved. Jeremiah had none of that. By modern standards, he failed completely.

But here we are, thousands of years later, still reading his words.

There's something we might be missing about leadership.

Jeremiah wept over the people who hated him (Jeremiah 9:1). He complained bitterly to God about his calling (Jeremiah 20:7-9). He was fully human. Frustrated. Exhausted. Sometimes ready to quit.

Yet he never stopped.

Why? Because the fire inside was bigger than the rejection outside.

"His word is in my heart like a fire," he wrote. "I am weary of holding it in" (Jeremiah 20:9).

And buried in all that rejection, Jeremiah spoke one of history's most hopeful promises. A new covenant. Not written on stone tablets. Written on human hearts (Jeremiah 31:31-34). A promise that pointed forward to something—someone—greater.

Maybe faithfulness isn't about winning.

Maybe it's about staying true to what burns inside us. Even when the room is empty. Even when the critics are loud. Even when the results never come.

The weeping prophet teaches us that some messages matter more than our comfort. Some callings outlast our lifetimes. Some seeds don't bloom until we're gone.

That's not failure.

That's legacy.$pt$, $q$2026-02-22T16:00:00Z$q$, $q$publish$q$, 84, $q$https://stevesammons.com/when-nobody-wants-to-hear-it/$q$, $q$https://sammons.substack.com/p/when-nobody-wants-to-hear-it$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1794, $q$When The Answer Is Silence$q$, $q$when-the-answer-is-silence$q$, $pt$BIG IDEA

Sometimes the breakthrough isn't getting an answer. It's learning to lead without one. The strongest leaders discover that unexplained suffering can shape us more than success ever could.

BACKGROUND

Job was a wealthy and respected man from the ancient land of Uz (see map of Uz). He had it all—family, fortune, influence. Then he lost everything in a single day. His story has puzzled philosophers and leaders for three thousand years.

STORY

Here's the part nobody tells you about Job:

He never got an explanation.

In a single morning, Job lost his livestock, his servants, and all ten of his children (Job 1:13-19). His health collapsed. His wife told him to curse God and die (Job 2:9).

Then his friends showed up.

For thirty-seven chapters, they tried to explain his suffering. You must have sinned. You must have failed. There must be a reason.

We do this too.

When things fall apart, we scramble for the formula. The lesson. The silver lining. We need the pain to make sense.

But here's what happens when God finally speaks (Job 38-41):

He doesn't explain anything.

Instead, He asks questions. "Where were you when I laid the earth's foundation?" (Job 38:4). "Can you bind the chains of the Pleiades?" (Job 38:31).

Not answers. Perspective.

Job's response? "My ears had heard of you, but now my eyes have seen you" (Job 42:5).

Something shifted. Not his circumstances. Him.

This is the leadership insight we miss: Real transformation rarely comes through explanation. It comes through encounter. Through trust built in darkness.

James tells us Job's story ends with perseverance and compassion (James 5:11). But the path there wasn't understanding—it was surrender.

The leaders who shape history aren't the ones with all the answers.

They're the ones who kept showing up when the answers didn't come.

Maybe that's where we are right now—in the silence between the question and something we can't yet see. Job's story suggests the silence itself might be the curriculum.

The question isn't whether we'll face seasons without answers.

The question is who we'll become in them.

I had the honor of attending this year's National Prayer Breakfast in Washington, DC, where Governor Bill Lee spoke. He's the Governor of Tennessee (where I live). His personal testimony of profound loss, unanswered grief, and eventual redemption through faith beautifully illustrates what it looks like to walk through silence and emerge transformed—much like Job.

https://www.youtube.com/watch?v=4cqsfvmEJ90&t=41s

This ties right back to the core of the post: sometimes the most powerful "answer" is the encounter with God in the quiet, leading us to keep showing up and serving anyway.$pt$, $q$2026-02-15T16:00:00Z$q$, $q$publish$q$, 85, $q$https://stevesammons.com/when-the-answer-is-silence/$q$, $q$https://sammons.substack.com/p/when-the-answer-is-silence$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1781, $q$When Everyone Else Is Wrong$q$, $q$when-everyone-else-is-wrong$q$, $pt$BIG IDEA

Sometimes the crowd isn't just mistaken. Sometimes the crowd is catastrophically wrong. And sometimes, leading well means building something nobody else believes in.

BACKGROUND

Noah lived in an age when violence and corruption had become normal. Scripture calls him "a preacher of righteousness" (2 Peter 2:5). He's the guy who built a massive boat in the desert because he trusted a warning nobody else could hear.

STORY

Imagine building a ship for 100 years while your neighbors laugh.

No rain in sight. No ocean for miles. Just a man, his family, and a project that makes zero sense to anyone watching.

That was Noah's life.

Genesis 6:9 says Noah was "righteous" and "blameless" in his generation. Not perfect. Not sinless. Just different. He walked with God when walking with God was deeply unpopular.

Here's what strikes me about Noah:

He didn't argue with his critics. He didn't write rebuttals. He didn't try to convince the skeptics.

He just built.

Day after day. Year after year. One board at a time.

Hebrews 11:7 tells us Noah acted "by faith" and "in holy fear." He took God seriously when nobody else would. And that faith became the vehicle—literally—that preserved humanity.

We often think leadership means having followers. Having buy-in. Having a coalition.

But sometimes leadership looks like building alone.

Noah's ark wasn't just a boat. It was a statement. A physical declaration that the world's direction was wrong. That judgment was coming. That there was another way.

The ark also points forward. Centuries later, another would come to save humanity from judgment—not through wood and pitch, but through a cross. Peter himself makes this connection (1 Peter 3:20-21). Noah's rescue was a preview of a greater rescue still to come.

Here's the takeaway:

Integrity doesn't need an audience. Faithfulness doesn't require applause. And doing the right thing rarely comes with a crowd.

Noah finished the ark. The rains came. Eight people were saved (Genesis 7:7).

Not a great return on investment by modern metrics. A massive do-over.

What are we building that nobody else understands yet?$pt$, $q$2026-02-08T16:00:00Z$q$, $q$publish$q$, 86, $q$https://stevesammons.com/when-everyone-else-is-wrong/$q$, $q$https://sammons.substack.com/p/when-everyone-else-is-wrong$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1779, $q$When the Old Way Stops Working$q$, $q$when-the-old-way-stops-working$q$, replace($pt$BIG IDEA

The hardest leadership moment isn't starting something new. It's letting go of what used to work. We don't get to pick when the world changes—only how we respond when it does.

BACKGROUND

Samuel was the last of an old order and the first of something new. For decades, he led Israel as a judge and prophet. Then everything shifted. The people wanted a king. His story sits at the hinge point of an entire nation's identity (1 Samuel 1-3[[semicolon]] 8[[semicolon]] 12[[semicolon]] 15-16).

STORY

Here's something we don't talk about enough:

Samuel did everything right.

He listened when others couldn't hear. As a boy, he recognized God's voice when even the priest missed it (1 Samuel 3:4-10). He grew into a leader the nation trusted. He settled disputes. He spoke truth.

And then the people said, "We want something different."

That stings.

"Give us a king," they demanded. "Like all the other nations" (1 Samuel 8:5). They weren't rejecting Samuel's competence. They were rejecting his whole approach. The system that had worked for generations suddenly felt outdated.

Samuel took it personally. Of course he did. We would too.

But here's what makes his response remarkable:

He didn't fight it.

He warned them. He told them exactly what a king would cost—their sons, their daughters, their land, their freedom (1 Samuel 8:11-18). He made sure they understood. Then he anointed the king anyway.

Not once. Twice.

The first king, Saul, fell apart. Samuel grieved deeply (1 Samuel 15:35). But he didn't give up. He went to Bethlehem and found David—a shepherd boy nobody expected (1 Samuel 16:11-13).

Samuel became the bridge.

Not the destination. The bridge.

Maybe that's the lesson we're circling around together. Sometimes our job isn't to be the final answer. It's to connect what was to what's coming. The old prophets pointed forward to something greater. Samuel's anointing of David created a royal line that would eventually lead to another unexpected king—one born in the same town of Bethlehem (Matthew 1:1-17).

Bridges don't get monuments.

But without them, nobody gets across.

The question isn't whether things will change. They will. The question is whether we'll grip tighter or hold open our hands. Whether we'll block the path or become part of it.

Samuel shows us what it looks like to steward transition instead of fighting it.

And maybe that's the kind of leader the moment needs.$pt$, '[[semicolon]]', chr(59)), $q$2026-02-01T16:00:00Z$q$, $q$publish$q$, 87, $q$https://stevesammons.com/when-the-old-way-stops-working/$q$, $q$https://sammons.substack.com/p/when-the-old-way-stops-working$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1775, $q$The Leader Who Wasn't Enough$q$, $q$the-leader-who-wasnt-enough$q$, $pt$BIG IDEA

The best leaders know they're not the final answer. They build something bigger than themselves—and then point beyond it.

BACKGROUND

David is history's most celebrated king. A shepherd who killed giants. A poet who wrote Israel's worship songs. A warrior who united a nation. He's the standard by which all other leaders get measured.

STORY

Here's the strangest detail about David's story: God told him no.

Not to a small request. To his biggest dream.

David wanted to build God's temple. The ultimate legacy project. The thing that would cement his name forever (2 Samuel 7:1-5).

God said no.

Think about that. This man killed Goliath as a teenager (1 Samuel 17). Wrote Psalm 23. United warring tribes. Danced in the streets when the Ark returned.

And his biggest dream? Someone else would finish it.

We hate this story.

We want leaders who complete things. Who cross finish lines. Who hold the trophy. Who have the highest level of integrity.

But David shows us something uncomfortable.

Even the greatest human leader isn't enough.

He failed spectacularly. Bathsheba. Uriah. A family torn apart by violence. For all his victories, David couldn't fix himself.

In Psalm 22, he wrote words of abandonment: "My God, my God, why have you forsaken me?" (Psalm 22:1). Words that would echo a thousand years later from another man's lips.

David wasn't the end of the story. He was pointing to someone.

To a greater King who would build an eternal temple—not of stone, but of people. To Jesus, "Son of David" (Matthew 1:1), who finished what David couldn't.

The best leaders understand this.

They gather resources for temples they won't build. They prepare successors for victories they won't see. They point to something beyond themselves.

David's legacy wasn't the temple. It was the promise. Not what he built, but who he pointed to.

The question for us isn't whether we're enough.

It's whether we're pointing somewhere.$pt$, $q$2026-01-25T16:00:00Z$q$, $q$publish$q$, 88, $q$https://stevesammons.com/the-leader-who-wasnt-enough/$q$, $q$https://sammons.substack.com/p/the-leader-who-wasnt-enough$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1721, $q$The Conquest That Couldn't Deliver$q$, $q$the-conquest-that-couldnt-deliver$q$, $pt$BIG IDEA

Sometimes we get everything we wanted. And discover it wasn't enough.

I've crossed a few finish lines. The confetti settles fast.

The greatest victories can still leave us restless. What if the goal was never really the goal?

BACKGROUND

Joshua led an entire nation into their promised land. He was Moses's right hand. A general. A conqueror.

His very name meant "salvation." He delivered on every promise. Yet something was missing.

STORY

Here's the strange part.

Joshua won. Every battle. Every city. Walls crumbled. Armies fled. The land was taken.

"Be strong and courageous," God told him (Joshua 1:9). Joshua obeyed. He crossed the impossible Jordan at flood stage (Joshua 3:15-17). He watched Jericho fall without a single siege weapon.

Total victory.

But centuries later, a letter to early believers drops a bomb: "If Joshua had given them rest, God would not have spoken later about another day" (Hebrews 4:8).

Wait.

Joshua's conquest—the whole thing—didn't actually deliver rest?

This hits close to home.

We chase the promotion. Get it. Still anxious.

We build the business. Launch it. Still empty.

We cross our Jordan. Take our promised land. And realize the land was never the point.

Joshua, at the end of his life, gathered the people. "Choose this day whom you will serve" (Joshua 24:15). He knew. The conquest was a shadow. The real rest—the soul-level peace we're all hunting—required something he couldn't provide.

Someone else.

Centuries later, another Joshua showed up. Same name. Different language.

Jesus.

"Come to me, all who are weary, and I will give you rest" (Matthew 11:28).

The first Joshua conquered land. The second Joshua conquered the thing that makes us restless in the first place.

We keep thinking the next achievement will satisfy. It won't. It can't.

Because rest was never waiting in the promised land.

It was waiting in a person.$pt$, $q$2026-01-18T16:00:00Z$q$, $q$publish$q$, 89, $q$https://stevesammons.com/the-conquest-that-couldnt-deliver/$q$, $q$https://sammons.substack.com/p/the-conquest-that-couldnt-deliver$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1705, $q$When Your Dream Gets You Thrown in a Pit$q$, $q$when-your-dream-gets-you-thrown-in-a-pit$q$, $pt$BIG IDEA

The path to influence rarely runs in a straight line. Sometimes the very gift that sets us apart is what puts us in danger. We're learning that the detours aren't delays—they're training grounds.

BACKGROUND

Joseph was the favored son of Jacob. He had prophetic dreams that predicted his family would bow to him. His story spans Genesis 37-50. He went from pit to prison to palace—and what happened in between changes everything we think we know about success.

STORY

Here's a seventeen-year-old with a coat that screams favoritism and dreams that sound like arrogance.

His brothers hated him for it.

Not disliked. Hated. The Hebrew word means they couldn't speak a peaceful word to him (Genesis 37:4).

So they sold him. Their own brother. For twenty pieces of silver.

This is where most of us would quit.

Joseph didn't.

He served Potiphar with excellence. Got promoted. Then got falsely accused and thrown in prison (Genesis 39:20). Another pit. Different walls.

Same response: he served with excellence.

The warden put him in charge of the other prisoners. Joseph interpreted dreams for the cupbearer and baker. The cupbearer got released and forgot about Joseph for two full years (Genesis 40:23).

Two. Years.

We want influence on our timeline. Joseph was being prepared on a different one.

When Pharaoh finally called, Joseph was ready. He interpreted the dream, proposed a solution, and got appointed second-in-command over all of Egypt (Genesis 41:40-41).

Thirteen years from pit to palace.

Here's what we're discovering together: Joseph didn't waste his waiting. He didn't grow bitter. He grew better. Every setback became a setup.

When famine hit, his brothers came begging for food. They bowed before him—just like the dreams predicted (Genesis 42:6). Joseph had every right to revenge.

He chose restoration instead.

"You meant it for evil," he told them. "But God meant it for good, to save many lives" (Genesis 50:20).

The brother who was sold became the savior of his family.

Sound familiar?

Centuries later, another man would be betrayed by those closest to him. Sold for silver. Condemned though innocent. He descended into darkness before rising to save everyone who rejected him.

Joseph's story whispers what Jesus's story shouts: betrayal doesn't have to be the end. It can be the beginning of something bigger than we ever dreamed.

The pit isn't your destination.

It's your training ground.$pt$, $q$2026-01-11T16:00:00Z$q$, $q$publish$q$, 90, $q$https://stevesammons.com/when-your-dream-gets-you-thrown-in-a-pit/$q$, $q$https://sammons.substack.com/p/when-your-dream-gets-you-thrown-in-a-pit$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1956, $q$When Someone Else Breaks the Deal$q$, $q$when-someone-else-breaks-the-deal$q$, $pt$BIG IDEA

Sometimes we inherit messes we didn't make. The question isn't whether we caused the problem. It's whether we'll step into the gap before everything falls apart.

BACKGROUND

Abigail lived around 1010 BC in ancient Israel. She was married to Nabal, a wealthy rancher with a terrible reputation. Her story in 1 Samuel 25 shows what happens when wisdom meets crisis.

STORY

Four hundred armed men were coming to kill everyone in the household.

And it wasn't her fault.

David—the future king—had protected Nabal's shepherds for months. Free of charge. His men never stole a single sheep. When shearing time came, David politely asked for some provisions.

Nabal's response? "Who is this David? Why should I give my bread to some runaway?" (1 Samuel 25:10-11)

Bad move.

David strapped on his sword. Four hundred men followed.

Here's where it gets interesting.

A servant ran to Abigail. Not to Nabal. The servant knew who could actually solve problems in that household.

We often think leadership means having the title. But real influence shows up in who people run to when things fall apart.

Abigail didn't waste time arguing with her husband. She loaded donkeys with bread, wine, grain, and meat. Then she rode out to meet an army.

Alone.

When she found David, she took full responsibility. "Let this wrong be on me," she said (1 Samuel 25:24). She didn't blame her husband publicly. She absorbed the failure and offered a path forward.

Then she said something remarkable.

She reminded David of his future. "The Lord will certainly make a lasting dynasty for you" (1 Samuel 25:28). She helped him see that revenge would stain his legacy.

David stopped.

Four hundred swords went back in their sheaths.

Abigail saved everyone—including David from himself.

Think about it. The best leaders don't just solve today's crisis. They help others avoid tomorrow's regret. Abigail points forward to someone greater who would intercede for us, taking our failures on himself so we could have a future (Romans 5:8).

The question isn't whether you caused the mess.

It's whether you'll step into it anyway.$pt$, $q$2026-01-06T16:23:53Z$q$, $q$publish$q$, 91, $q$https://stevesammons.com/when-someone-else-breaks-the-deal/$q$, $q$https://sammons.substack.com/p/when-someone-else-breaks-the-deal$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1485, $q$You're Not Samson$q$, $q$youre-not-samson$q$, $pt$We love to criticize Samson.

We call him reckless. Violent. A womanizer. We read his story and shake our heads at how badly he blew it.

But here's the problem.

Think about this. We may have been reading ourselves into the wrong character.

Samson's story is recorded in the book of Judges. This book has two groups. There are the judges. And there is Israel.

The judges were raised up by God. The Spirit came upon them. They brought deliverance. They secured rest for the land.

Israel? They did evil in the eyes of the Lord. They worshiped foreign gods. They ignored the judges God sent. And when each judge died, they became worse than before.

The pattern repeats six times.((Sammons, Steven. 2025. “Six Judges, One Pattern.” Blog. Six Judges, One Pattern, December 22. https://stevesammons.com/six-judges-one-pattern/.))

God sends a deliverer. Israel refuses to listen. The deliverer saves anyway. Israel sinks deeper into unfaithfulness.

The problem was never the judges. The problem was Israel.

So why do we spend so much energy attacking Samson?

Modern commentators call him a violent, sex-addicted failure. They pick apart his flaws. They use him as a warning of what not to become.

But the author of Hebrews saw something different.

He lists Gideon, Barak, Samson, and Jephthah among the heroes of faith. He says they conquered kingdoms, shut the mouths of lions, and routed foreign armies. He says the world was not worthy of them (Hebrews 11:32–38).

Scripture's assessment is clear. Ours has been wrong.

Here's the truth that changes everything.

We're not Samson. We are Israel.

We are not the strong ones who fell. We are the faithless ones who need saving.

Samson wasn't the failure in the story. He was the rescue. Flawed? Yes. But faithful in his calling. Empowered by the Spirit. Raised up by God to deliver people who didn't deserve it.

Sound familiar?

Samson's greatest moment came at the end.

Blinded. Mocked. Chained between the pillars of a pagan temple.

He prayed one last time. And in his death, he killed more enemies than in his entire life.

His victory was accomplished through his death.

Barry Webb, a Judges scholar, put it this way: "In this most unlikely figure, we see possibly more clearly than anywhere else in the Old Testament, the shape of things to come."((Barry G. Webb, « The Book of Judges » on Wm. B. Eerdmans Publishing Co, December 23, 2025))

A deliverer rejected by his own people.

Handed over to pagan rulers.

His saving work was completed in death.

A death that crushed the enemy and laid the foundation for full deliverance.

This is the gospel, promised beforehand.

Every judge points forward. To a better Judge. One who would lay down His life to achieve His greatest victory.

We needed a judge who wouldn't stay dead.

And that's exactly who came.

So let's stop criticizing Samson.

Start seeing ourselves in Israel.

And fix our eyes on the One all the judges were pointing to.$pt$, $q$2025-12-28T15:58:00Z$q$, $q$publish$q$, 92, $q$https://stevesammons.com/youre-not-samson/$q$, $q$https://sammons.substack.com/p/youre-not-samson$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1491, $q$The Christmas Story Is a Translation$q$, $q$the-christmas-story-is-a-translation$q$, $pt$BIG IDEA

We have two Christmas stories in the Bible. Not contradictory accounts. Two windows into the same event, written for different people standing in different places. That difference turns out to be the point.

BACKGROUND

Matthew wrote for Jewish readers. Luke wrote for a Greek named Theophilus. Same birth. Same Savior. Different doorways into the meaning.

STORY

Matthew gives us a genealogy. Wise men from the East. A paranoid king. A flight to Egypt. Prophecy fulfilled at every turn. His audience needed to see Jesus in the line of Abraham and David.

Luke gives us angels appearing to shepherds. A manger because there was no room. An old man named Simeon. A prophetess named Anna. The poor receiving the first announcement. His audience needed to know this Savior was for everyone.

There's a temptation to flatten this. To harmonize the accounts into one seamless narrative and miss what each writer was doing.

Matthew and Luke weren't stenographers. They were interpreters.

They took the same truth and made it accessible. They asked: What does this mean for this person, in this moment?

This is what leaders learn to do.

Purpose doesn't change. But how we communicate it must.

A mission statement is not a translation. That's transmission—important, but incomplete. Translation asks different questions: What matters to this person? What framework do they already have? What language will carry this truth into their world?

But there's a deeper layer here.

The Christmas story doesn't just illustrate translation. It is the ultimate translation.

The Incarnation is God translating Himself.

The infinite became finite. The Word became flesh (John 1:14). Not because God's nature changed. Because love moves toward understanding.

He didn't send a memo from heaven. He came as a baby—dependent, vulnerable, human. Not because it was efficient. Because it was the only way we could truly receive Him.

This is the pattern.

You don't throw truth at people and hope it lands. You learn their language. You enter their world. You translate into terms they can hold.

Matthew knew his readers. Luke knew his. And they told the same story differently—faithfully.

The manger was not a retreat from glory. It was the clearest communication of it.

P.S., There is no historical evidence one way or the other that Luke and Matthew ever met. I put them together in the photo because it helped me tell this story.$pt$, $q$2025-12-25T15:23:00Z$q$, $q$publish$q$, 93, $q$https://stevesammons.com/the-christmas-story-is-a-translation/$q$, $q$https://sammons.substack.com/p/the-christmas-story-is-a-translation$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1477, $q$The Man Who Packed Without a Map$q$, $q$the-man-who-packed-without-a-map$q$, $pt$BIG IDEA

Real leadership starts when the GPS goes dark. The greatest moves require leaving before you know where you're going.

BACKGROUND

Abraham is the father of faith. He's mentioned in three major world religions. His story shaped billions of lives. And it all started with one terrifying question.

STORY

He was 75 years old. Wealthy. Settled. Comfortable.

Then God said four words that changed everything: "Leave your father's household" (Genesis 12:1).

No destination given. No timeline. No strategic plan.

Just go.

Here's what's strange. Abraham went.

He packed up his wife, his nephew, and everything he owned. He walked away from the only home he'd ever known. He headed toward a place he'd never seen.

Hebrews 11:8 says he "obeyed and went, even though he did not know where he was going."

That's not reckless. That's faith.

Most leaders won't move until they see the whole staircase. Abraham moved when he could only see one step.

And that step was enough.

God made him a wild promise. "Look at the sky. Count the stars. That's how many descendants you'll have" (Genesis 15:5).

Abraham was old. His wife Sarah was old. They had no children.

It made no sense.

But "Abraham believed the Lord, and he credited it to him as righteousness" (Genesis 15:6).

This is the pattern. Trust first. Understanding later.

Romans 4:20-21 puts it plainly: "He did not waver through unbelief... being fully persuaded that God had power to do what he had promised."

Then came the hardest test of all.

God asked Abraham to sacrifice Isaac. His only son. The one he waited 25 years for. The child of the promise (Genesis 22:2).

This makes no sense either.

But Abraham got up early the next morning and started walking.

Why? Hebrews 11:19 tells us. Abraham believed God could raise the dead if He had to.

He trusted the promise-maker more than the promise.

Here's what Abraham teaches us about leadership.

Clarity isn't required. Courage is.

The path becomes clear by walking it. Not by staring at it.

Abraham didn't have a five-year plan. He had faith in a faithful God.

And that faith pointed forward. Centuries later, another Father would offer His only Son on a hill. This time, no ram appeared. This time, the sacrifice was complete.

Jesus is where Abraham's faith was always heading.

What's God asking you to leave behind?

You might not see the destination. That's okay.

The first step is the hardest one.

Take it anyway.$pt$, $q$2025-12-14T15:28:00Z$q$, $q$publish$q$, 94, $q$https://stevesammons.com/the-man-who-packed-without-a-map/$q$, $q$https://sammons.substack.com/p/he-left-before-he-knew$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1469, $q$The Cost of Knowing$q$, $q$the-cost-of-knowing$q$, $pt$Moses saw more than anyone.

Burning bush. Parted sea. Forty days in the cloud. God's glory, face to face.

No one had more access.

Which is precisely why his punishment was so severe.

One moment of doubt. One extra strike of the rock. And the man who led two million people out of Egypt would never set foot in the Promised Land.

It seems harsh. 

It feels disproportionate.

But here's what we miss: the punishment was proportional to the privilege.

Moses knew. And in front of all those people, he acted as if maybe God wasn't quite committed. Maybe Yahweh needed convincing.

The wages of knowing and then questioning are higher than the wages of ignorance.

This is why teachers are judged more strictly. Why leaders carry a heavier weight. Why does the pastor's failure land differently than the new believer's stumble?

Not because God plays favorites.

Because revelation creates responsibility.

And we still do it.

"Lord, please be with us."

It's the most common prayer in the church. And it's a lie. He's already there. He promised. He moved in.

The question isn't whether He's present—it's whether we'll act like it.

Have you ever thought that every time we pray please be with us, we're striking the rock again.

Jesus spent forty days in the wilderness too. No manna. No quail. No water from stone. And He passed the test Israel failed.

Now the Spirit lives in every believer—not in smoke above a tent, but in you. Permanently. Irrevocably.

The question was never God's faithfulness.

It was always ours.$pt$, $q$2025-12-10T23:11:21Z$q$, $q$publish$q$, 95, $q$https://stevesammons.com/the-cost-of-knowing/$q$, $q$https://sammons.substack.com/p/the-cost-of-knowing$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1266, $q$Be a Mordecai: The Quiet Power of Encouragement$q$, $q$be-a-mordecai-the-quiet-power-of-encouragement$q$, $pt$The Story of Esther: A Quick Overview

Long ago, in the mighty Persian Empire, a young Jewish woman named Esther found herself in an unimaginable position: chosen as queen. But her rise to royalty wasn’t just luck or beauty-it was guided by her wise cousin, Mordecai. When a plot to destroy the Jewish people emerged, it was Mordecai who encouraged Esther to act, reminding her that she might have come to her royal position “for such a time as this.” Through courage, faith, and the steady support of Mordecai, Esther spoke up, saved her people, and established the joyful festival of Purim.

But while Esther’s bravery shines, let’s not forget the quiet heroism of Mordecai-the encourager, the guide, the one who believed in Esther even when she doubted herself.

Why We All Need a Mordecai

In every season of life, we face moments of uncertainty, fear, or transition. Sometimes we’re called to step up, but we hesitate. That’s when a Mordecai makes all the difference-a friend, mentor, or family member who sees our potential, nudges us forward, and reminds us of our purpose.

Mordecai didn’t have the crown, but he had influence. He didn’t command armies, but he inspired courage. His quiet words changed the course of history.

How to Be a Mordecai in Someone’s Life

Speak Encouragement -Sometimes, all it takes is a kind word or a gentle reminder: “You can do this. You’re here for a reason.” Your encouragement might be the spark someone needs to step into their moment.

See Potential - Look for the hidden strengths in others. Like Mordecai, believe in people before they believe in themselves. Your faith in them can help them find their own.

Offer Wisdom - Mordecai didn’t push Esther blindly-he offered wise counsel and perspective. Share your experience and insight with humility, helping others see the bigger picture.

Stand By Them - Even after Esther became queen, Mordecai stayed close, supporting her from the sidelines. Be present for others, cheering them on through every challenge and victory.

Celebrate Their Courage - When those you encourage take brave steps, celebrate with them! Rejoice in their growth and success, knowing you played a part in their journey.

Uplifting Challenge: Who Can You Encourage Today?

You don’t need a title, a platform, or a stage to make a difference. All you need is a heart willing to see, support, and speak life into someone else’s story.

Be a Mordecai

Be the voice that says, “You’ve got this.” Be the steady presence that helps someone rise. You never know-your encouragement might just change the world, one person at a time. Who has been a Mordecai in your life? And who can you encourage today? Let’s lift each other up and keep the legacy of quiet, powerful support alive

Source: The story of Esther can be found in the Bible Esther 1-10.$pt$, $q$2025-05-14T13:07:11Z$q$, $q$publish$q$, 96, $q$https://stevesammons.com/be-a-mordecai-the-quiet-power-of-encouragement/$q$, null, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (802, $q$Messy Grace: Lessons from Jesus on Loving Through Difficult Relationships$q$, $q$messy-grace-lessons-from-jesus-on-loving-through-difficult-relationships$q$, replace($pt$Here are biblical examples that demonstrate Jesus entering into difficult relationships and messy situations with love and grace:

1. Jesus and Judas (Matthew 26:14-16, 47-50) Despite knowing Judas would betray Him, Jesus treated him with kindness and included him in His inner circle. Even at the Last Supper, Jesus washed Judas’s feet, exemplifying humility and love.

2. Jesus and Peter (Luke 22:54-62[[semicolon]] John 21:15-19) After Peter denied Jesus three times, Jesus didn’t reject him. Instead, He restored their relationship by asking Peter three times if he loved Him, reaffirming Peter’s calling to lead and serve.

3. The Woman at the Well (John 4:7-26) Jesus engaged with a Samaritan woman who had a complicated past. He didn’t condemn her but offered her living water, demonstrating compassion and breaking social barriers.

4. The Leper (Matthew 8:1-4) When society shunned lepers, Jesus not only healed a man with leprosy but touched him—a profound act of love and acceptance.

5. Jesus on the Cross (Luke 23:34) As He was crucified, Jesus prayed for those who were killing Him: “Father, forgive them, for they do not know what they are doing.” This ultimate act of love shows His commitment to forgiveness even in extreme adversity.

6. Zacchaeus the Tax Collector (Luke 19:1-10) Jesus sought out Zacchaeus, a man despised for his corruption, and invited Himself to Zacchaeus’s home. This act of inclusion led to Zacchaeus’s repentance and transformation.Jesus and the Pharisees (Matthew 23:1-36)

7. Jesus and the Pharisees Jesus confronted the Pharisees with grace and truth, pointing out their hypocrisy while still offering them a path to redemption.

8. Jesus and the Adulterous Woman (John 8:1-11) Jesus showed compassion and forgiveness to the woman caught in adultery, challenging her accusers and offering her a new start.

9. Jesus and His Family (Mark 3:20-21, 31-35) Jesus faced opposition from His own family, who didn’t understand His mission. He responded by defining His family as those who do God’s will.

10. Jesus and the Rich Young Ruler (Mark 10:17-22) Jesus engaged with the rich young ruler, who was difficult due to his attachment to wealth. Jesus challenged him to follow Him fully.

11. Jesus and the Disciples’ Disputes (Luke 9:46-48, 22:24-30) Jesus addressed the disciples’ arguments and competitiveness, teaching them about humility and service.

12. Jesus Walked Away from Toxic People (Luke 4:28-30[[semicolon]] Matthew 15:14) In situations where people were hostile or unrepentant, Jesus sometimes walked away or allowed them to leave, demonstrating discernment in dealing with toxicity while remaining focused on His mission.

Walking away in the context of people behaving badly or making life difficult for one another is a nuanced situation. While Jesus often walked away from toxic or unrepentant individuals, His actions were always guided by discernment and mission focus. Here’s how this principle might apply to believers:

Walking Away Isn’t Limited to Evangelism

Jesus didn’t only walk away from those rejecting His message of salvation (e.g., Matthew 10:14). He also disengaged from situations where continuing would have been unproductive or harmful, such as with Herod (Luke 23:9) or the crowd demanding miracles without faith (Matthew 8:18). This shows that walking away can apply to relational dynamics, even among believers, when toxicity persists.

2. Dealing with Believers Behaving Badly

When professed believers act in ways that disrupt unity or harm relationships, biblical principles still apply. Jesus emphasized reconciliation and forgiveness (Matthew 18:15-17), but He also taught boundaries. For example, Paul advised believers to avoid divisive individuals after multiple warnings (Titus 3:10). This approach balances grace with accountability.

3. Tests Before Walking Away

Before deciding to walk away, it’s essential to test whether the action reflects Christ-like behavior:

• Have efforts been made for reconciliation? Jesus taught the importance of addressing issues directly and seeking peace (Matthew 5:23-24[[semicolon]] Matthew 18:15-17).

• Is the behavior persistently harmful or unrepentant? Walking away may be appropriate if someone refuses correction and continues causing harm.

• Is the decision rooted in prayer and discernment? Jesus often withdrew to pray before making significant decisions (Luke 6:12).

4. The World Is Watching

How believers handle conflict publicly matters. Families, colleagues, and communities observe whether we embody Christ-like love and forgiveness—or fall into gossip and division. Paul reminds us that our conduct should reflect lives “worthy of the calling” (Ephesians 4:1-3). Walking away must be done with humility and grace, leaving no room for bitterness.

Ultimately, walking away is not about abandoning relationships but recognizing when continuing engagement hinders spiritual growth or unity. It’s an act of trust—entrusting the situation to God while remaining committed to living out His love in all circumstances.$pt$, '[[semicolon]]', chr(59)), $q$2025-04-13T19:05:32Z$q$, $q$publish$q$, 97, $q$https://stevesammons.com/messy-grace-lessons-from-jesus-on-loving-through-difficult-relationships/$q$, null, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (376, $q$What Kind of God Would Bless a Snake?$q$, $q$what-kind-of-god-would-bless-a-snake$q$, $pt$Have you ever felt like your past mistakes or family history are too messy for redemption? The story of Judah and Tamar in Genesis 38 shows that even the most complicated situations can be part of a greater plan.​

Judah's Story

Judah, one of Jacob's sons, made several poor choices. He failed to uphold his responsibilities, especially towards his daughter-in-law, Tamar. After the deaths of his two sons, Er and Onan, Judah promised Tamar that his youngest son, Shelah, would marry her. However, he didn't follow through, leaving Tamar in a vulnerable position.​

Tamar's Bold Move

Determined to secure her place in the family and fulfill her rights, Tamar took matters into her own hands. She disguised herself and became pregnant by Judah, resulting in the birth of twins, Perez and Zerah. This act, while unconventional, ensured the continuation of a lineage that would lead to King David and, eventually, Jesus Christ.​

A Message of Redemption

This narrative highlights that God's plans often work through imperfect people and situations. It serves as a reminder that no matter our past, redemption is possible.​

Modern-Day Parallel

Dr. Gerry Breshears discusses this story and connects it to contemporary issues, such as the courage of Rachel Denhollander in exposing abuse within USA Gymnastics. His insights emphasize that truth and justice can emerge from even the darkest circumstances

https://youtu.be/7J9bKLAg00I

The surprise of Gerry’s talk is that he takes us from the story of Judah and Tamar and brings it full circle to today. From the ugliness of Judah to Rachel Denhollander and her new book What Is a Girl Worth?: My Story of Breaking the Silence and Exposing the Truth about Larry Nassar and USA Gymnastics. 

From a story in the Bible to a story today of truth and grit. His whole talk is worth a listen and is available to listen to on Soundcloud.

About Dr. Gerry Breshears

Dr. Gerry Breshears is a Professor of Theology at Western Seminary in Portland, Oregon. Dr. Breshears is passionate about the transforming power of the gospel, as it “brings freedom from guilt, shame, fear, and defilement before God.” He has taught at numerous Bible colleges and seminaries around the world, in countries such as Lebanon, Ukraine, Netherlands, Taiwan, Poland, Canada, and the Philippines. Dr. Breshears serves as a preaching elder at Grace Community Church. He and his wife, Sherry, have been married since 1968 and have two sons, one daughter, and are enjoying their season of life as grandparents.

About Judah

Judah was a pivotal figure in the Hebrew scriptures, born to Jacob and Leah around 1600 BCE during the second millennium. An instrumental character in the early formation of Israelite tribes, Judah married Shua's daughter, an unnamed Canaanite woman. They had three sons together - Er, Onan, and Shelah. Later, under complex circumstances, Judah fathered twin boys, Perez and Zerah, with his daughter-in-law Tamar.

Despite the moral complexities of his early life, including his role in selling his brother Joseph into slavery, Judah eventually emerged as the progenitor of the royal lineage leading to King David and, ultimately, Jesus Christ. His story, which spans approximately 119 years according to biblical accounts, underscores the transformative power of repentance and redemption.

Judah's enduring legacy is evident in the tribe named after him, one of the most significant of the twelve tribes of Israel. Today, his life continues to be a subject of theological exploration and discussion.

About Tamar

Tamar was a significant figure in the Hebrew scriptures during the second millennium BCE. Initially married to Judah's sons Er and Onan, both of whom died leaving her childless, Tamar secured her future through a strategic plan that led to her bearing twin sons, Perez and Zerah, with Judah himself. Her actions had a profound impact on biblical lineage, leading to the birth of King David and eventually, Jesus Christ. Her life represents resilience and resourcefulness, significant themes in biblical studies.$pt$, $q$2019-07-10T10:23:00Z$q$, $q$publish$q$, 98, $q$https://stevesammons.com/what-kind-of-god-would-bless-a-snake/$q$, null, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
