-- Generated by songs/supabase/export_posts.py. Run in Supabase > SQL Editor after schema.sql.
-- 52 scheduled and 46 published Bible-character posts.

-- Part 3 of 5.

insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1932, $q$Give Small Beginnings a Fair Chance$q$, $q$give-small-beginnings-a-fair-chance$q$, $pt$People need room to begin before they can become skilled. A child's first page of writing will have mistakes. A new volunteer may need help with a simple task. If we judge only what is missing, we can miss the effort that deserves our care.

Zechariah (zeh-kuh-RYE-uh) spoke to people who were rebuilding. He was a prophet, someone called to deliver God's message. Around 520 BC, more than five centuries before Jesus, he encouraged a Jewish community that had returned after being forced from its homeland by Babylon, an empire based in today's Iraq.

They were rebuilding the temple in Jerusalem, their place of worship. Its site lies within the eastern side of today's Old City. The map and background page helps place that work in the city we know now.

Their governor, Zerubbabel (zeh-RUH-buh-behl), had laid the temple's foundation. Much remained unfinished. Through Zechariah, God promised that the same man would see the work through (Zechariah 4:9).

Then came a question: “Who dares despise the day of small things” (Zechariah 4:10, NIV).

Despise means to look down on something. In this case, the warning concerned work that had not yet reached its full size. The foundation mattered before the building was complete.

The passage also placed the work in God's hands. Success would depend on his Spirit, beyond the strength or power people could gather (Zechariah 4:6). This was a promise about their temple. It does not mean every project we start is certain to succeed.

Still, I hear a question worth bringing into ordinary life: Am I giving a beginning a fair chance, or measuring it only against a finished result?

That matters when someone brings us work they are still learning to do. We can name a sentence that communicates clearly, then help with the next one. We can show a volunteer how to do a task and stay nearby while they try it.

That kind of help is honest. It notices mistakes while making room for growth. Empty praise gives a learner little to use. A specific word of encouragement and a useful next step give them something to work with.

This week, look for one beginning you can support. Give it your attention before giving it a score. Help the person see what is already taking shape and what they can try next. Small work can deserve serious care.$pt$, $q$2026-12-13T22:00:00Z$q$, $q$future$q$, 41, null, null, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (2748, $q$Doubt Does Not Have to End the Conversation$q$, $q$doubt-does-not-have-to-end-the-conversation$q$, $pt$I want to be honest about what I find hard to believe. Hiding a question can leave me alone with it. Saying it aloud gives someone a chance to listen, and gives me a chance to learn something I could not see before.

Sarah had a question like that. She was Abraham's wife, and they had grown old without having a child together. God had promised Abraham a son through Sarah. By then, having a baby seemed beyond anything their bodies could do (Genesis 17:15–21).

One day, three visitors arrived at their camp near Mamre (MAM-ree), in the area of Hebron (HEE-bruhn). That city is in today's West Bank, about 19 miles south of Jerusalem. We do not know exactly where their tent stood.

Sarah listened from the tent entrance while the visitors ate. One said she would have a son about that time the next year. She laughed to herself. She and Abraham were old. The promise did not fit what she knew about her life (Genesis 18:1–12).

The Lord asked why she laughed. Afraid, Sarah denied it. The conversation exposed her doubt, but the promise remained. God had not made the future depend on her giving a polished answer (Genesis 18:13–15).

Later, Sarah gave birth to a son named Isaac (EYE-zuhk). She said, “God has brought me laughter” (Genesis 21:6, NIV). The same woman who had laughed in disbelief could now invite others to share her joy.

I do not read this as a promise that every longed-for outcome will happen. Sarah's story concerns a particular promise God made to her family. It gives me no reason to blame someone whose waiting ends differently.

What stays with me is the room between her first reaction and the rest of her story. Her first response was not her last word.

That matters when I feel certain a conversation will go badly, or assume that a person cannot change. I can name my concern without pretending I already know the ending. I can ask what I might be missing. I can listen for an answer instead of rehearsing my objection.

If a friend offers to make things right, I can ask what that would look like. A clear question leaves room for a real response.

Faith can begin with an honest sentence: I am having trouble believing this.

I want to leave room for the next sentence too.$pt$, $q$2026-12-06T22:00:00Z$q$, $q$future$q$, 42, null, null, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1948, $q$Share the Hope You Notice$q$, $q$share-the-hope-you-notice$q$, $pt$Hope can be hard to carry alone. When someone notices a reason to keep going and shares it with me, the day can feel different. I want to offer that kind of encouragement: something honest and specific that helps another person see beyond the difficulty in front of them.

Anna was an elderly Jewish widow and prophet, a person who spoke for God. Luke introduces her at the temple, the great center of Jewish worship in Jerusalem. The temple stood on a raised site in the eastern part of what is now the Old City. The ancient temple building no longer stands.

Prayer and worship shaped Anna's life. Luke says she worshiped “night and day” (Luke 2:37, NIV). She had known the loss of her husband, yet the story shows her still taking part in the life of her people.

Then Mary and Joseph brought the infant Jesus to the temple, following their people's religious customs. Another worshiper had just praised God for the child when Anna came up to the family (Luke 2:22–38).

She thanked God. Then she spoke about Jesus to people who were hoping God would bring deliverance to Jerusalem. In other words, they were looking for God to rescue and restore his people (Luke 2:38).

Anna's hope became something she shared. Her part in the story was brief, but it reached beyond her own experience. She turned toward people who were waiting too.

I find that generous. She could give thanks and also help someone else see a reason for hope. The story makes me think about encouragement as a form of attention: noticing something worth naming, then taking the trouble to say it.

That can be simple. If someone is learning a difficult task, I can point to a skill they have gained. If a friend is worn down by caring for others, I can name the care I see and offer help. Specific words give encouragement something solid to rest on.

I do not need to promise that everything will turn out well. I can listen to what is hard and still recognize what is good. Both can belong in the same conversation.

Anna reminds me that a reason for hope is worth sharing. Today, I want to notice one real thing that could encourage someone and tell them what I see.

It may be a small gift. It is still a gift I can give.$pt$, $q$2026-11-29T22:00:00Z$q$, $q$future$q$, 43, null, null, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (2725, $q$Let People Be More Than a Label$q$, $q$let-people-be-more-than-a-label$q$, $pt$I want to leave room for people to change. If I reduce someone to a job, a mistake, or a reputation, I may stop listening before they speak. A label can become the only thing I see, even when a person is taking a new step.

Matthew was a tax collector who became one of Jesus's twelve closest followers. When Jesus called him, he was sitting at his collection booth. This was near Capernaum (kuh-PERR-nay-uhm), a lakeside town in what is now northern Israel. Its ruins stand on the northwestern shore of the Sea of Galilee.

Tax collectors worked within the system of rulers who controlled the region. Their work brought them suspicion and resentment. The story does not list Matthew's personal offenses. It does show how strongly some people objected to sharing a table with people in his line of work.

Jesus spoke two words to Matthew: “Follow me” (Matthew 9:9, NIV). Matthew stood up and went with him.

The next scene is a meal. Jesus and his followers ate with tax collectors and others described as sinners. Some religious teachers questioned why Jesus would eat with such people (Matthew 9:10–11).

Jesus answered by comparing his work to a doctor's care. People who are sick need help. He also pointed the teachers toward mercy (Matthew 9:12–13). He made room at the table for people who needed a different direction in life.

What catches my attention is that Jesus addressed Matthew as someone who could respond. Matthew's occupation was part of his story, but it did not prevent an invitation. The response belonged to Matthew, and he took it.

That challenges the way I might describe someone else. Calling a coworker unreliable can end the conversation before I ask what happened. I can name the missed deadline clearly, explain its effect, and ask what would help us keep the next agreement. The problem stays visible. So does the person.

Leaving room for change does not require instant trust. Trust can grow as someone follows through. I can pay attention to that evidence instead of repeating an old judgment every time their name comes up.

Matthew's story invites me to look again. Is there someone I have stopped seeing because I think I already know the whole story?

I want my next conversation to leave room for an answer I have not heard yet.$pt$, $q$2026-11-22T22:00:00Z$q$, $q$future$q$, 44, null, null, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (2718, $q$Give Care a Practical Form$q$, $q$give-care-a-practical-form$q$, $pt$When someone depends on me, love needs a practical form. Concern matters, but it cannot make a meal or arrange a ride by itself. I want to notice what care requires and do the part that is within my reach.

Jochebed (JAHK-uh-bed) was the mother of Moses, who would later lead the Israelites out of slavery in Egypt. His life began under a threat. Egypt's king had ordered that newborn Hebrew boys be thrown into the Nile River (Exodus 1:22).

Her story belongs to the world of the Nile Delta in northern Egypt, where the river spreads toward the sea north of modern Cairo. The Bible does not identify the exact riverbank where she acted.

Jochebed hid her baby for three months. When she could no longer keep him hidden, she made a basket from river plants and sealed it against the water. She placed him among the reeds at the river's edge. His older sister watched from a distance (Exodus 2:1–4).

The king's daughter found the crying child and felt compassion for him. His sister offered to find a woman to nurse him. She brought back his own mother. Jochebed cared for her son until he was older, then brought him to the king's daughter, who adopted him (Exodus 2:5–10).

Hebrews remembers that Moses's parents acted “by faith” (Hebrews 11:23, NIV). Their faith had something to do with the way they protected a child.

I notice how practical the care was. There was hiding, a basket made ready, and a place chosen among the reeds. Exodus describes a child placed at the bank, with his sister watching. Each detail matters because this was a real life in danger.

The story makes me look at the gap between feeling concerned and offering useful help. A person caring for a sick relative may need groceries brought to the door. A neighbor with a broken car may need a ride. I can ask what would help most and listen carefully before deciding what to offer.

I cannot promise to solve everything. I can be clear about what I can offer, agree on a time, and follow through. That makes my help something another person can count on.

Jochebed's story leaves me with a simple question: what does care need to become in my hands today?

I want to answer with something I can actually do.$pt$, $q$2026-11-15T22:00:00Z$q$, $q$future$q$, 45, null, null, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (2704, $q$Leave Room for an Answer$q$, $q$leave-room-for-an-answer$q$, $pt$When I ask someone for help, I want to understand something I may have missed. That takes more than asking a question. I need to leave room for an answer that could change what I do next.

Cornelius (kor-NEE-lee-us) was a Roman army officer. He lived in Caesarea (see-zuh-REE-uh), a port on the coast of present-day Israel, about thirty miles north of Tel Aviv. He prayed regularly and gave generously to people in need (Acts 10:1–2).

An angel told him to send for Peter, one of Jesus's followers. Cornelius sent messengers and gathered his relatives and close friends. He was ready to hear what Peter would say (Acts 10:3–8, 24).

This meeting crossed a real divide. Peter was Jewish. Cornelius was not. Before the visit, God had shown Peter that he should not treat another person as unclean. Peter came into the house, and Cornelius explained why he had sent for him (Acts 10:28–33).

The officer did not use the gathering to give orders. He told Peter that they were there before God to listen. Peter, too, had something to learn. He said, “God does not show favoritism” (Acts 10:34, NIV).

Peter spoke about Jesus's life, death, and resurrection. As he spoke, the Holy Spirit came upon those listening. Peter called for them to be baptized. They asked him to stay for a few days (Acts 10:36–48).

What stays with me is the room Cornelius made for that message. His work involved authority. In his home, he took the place of a learner. His prayers led to a practical response: he sent for someone, welcomed him, and listened.

I can ask for advice and still have my defense ready before the other person finishes. I can invite someone to explain a problem while hoping they will confirm the answer I already prefer. The question sounds open. My response may close it.

Cornelius gives me a different picture. Being responsible for others does not mean I have nothing left to receive. I can listen without losing my responsibility to think carefully about what I hear.

At the next conversation where I need help, I can ask a clear question and let the answer finish. Then I can name what I learned and decide what needs to change.

I want my willingness to learn to show up in what I do afterward.$pt$, $q$2026-11-08T22:00:00Z$q$, $q$future$q$, 46, null, null, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (2698, $q$Make Room for Someone Else's Joy$q$, $q$make-room-for-someone-elses-joy$q$, $pt$I want the people I love to feel free to bring me their good news. That means I need to welcome it without turning the conversation back to myself. Their joy can deserve my full attention even when I have something important happening, too.

Elizabeth (ee-LIZ-uh-beth) gives me a picture of that welcome. She was the mother of John the Baptist, who would later prepare people for Jesus. Before John was born, she and her husband had reached old age without children. Luke describes them as faithful to God (Luke 1:5–7).

Then Elizabeth became pregnant. She spoke of the pregnancy as God's kindness to her after the shame she had experienced among other people (Luke 1:24–25).

During her sixth month, her relative Mary came to visit. Mary was carrying Jesus. Elizabeth lived in the hill country of Judea (joo-DEE-uh), the region around Jerusalem. Christian tradition remembers their meeting at a site about five miles from Jerusalem's Old City, though Luke does not name the town.

When Elizabeth heard Mary's greeting, her baby leaped. Filled with the Holy Spirit, she called Mary blessed and welcomed her as the mother of her Lord. She said, “Blessed is she who has believed” (Luke 1:45, NIV). Mary stayed with her for about three months (Luke 1:39–56).

Elizabeth's own life was changing. Yet her words made room for what God was doing in Mary's life. She named it aloud. Her welcome did not require Mary to make her news smaller. Both women could give thanks in the same home.

That welcome asks something simple of me. When a friend shares good news, I can stay with their story. I can ask what it means to them. I can resist following their first sentence with a longer account of my own experience.

I do not have to pretend that every part of my life is settled before I celebrate with someone. Joy and an unanswered hope can exist in the same person. I can be honest about my own life and still offer a kind, interested response.

For me, that might begin with putting down my phone and asking one more question. It might mean naming the work I saw someone put in, or simply saying that I am glad they told me.

I want my attention to say what Elizabeth's welcome showed: there is room here for your joy.$pt$, $q$2026-11-01T22:00:00Z$q$, $q$future$q$, 47, null, null, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (2687, $q$When Faith Becomes a Bargain$q$, $q$when-faith-becomes-a-bargain$q$, $pt$Faith matters to me because I need help seeing beyond what I want. But I can turn prayer into a bargain: I will do the right religious things, and God will make my plans work. That leaves little room for God to change the plans—or me.

Micah (MY-kuh) was a man who lived in Israel before it had kings. He is not the later prophet whose name appears on a Bible book. His home was in the hills of Ephraim (EE-fray-im), part of the central hill country north of Jerusalem, in today's West Bank. Its exact location is unknown.

His story starts with stolen silver. Micah admitted taking it from his mother and returned it. She then used some of it to have an idol made. It went into his house, where he had his own place of worship (Judges 17:1–5).

Later, Micah hired a young man from Israel's priestly tribe to serve as his priest. Micah took this as a reason to expect God's favor: “Now I know that the Lord will be good to me” (Judges 17:13, NIV).

The next chapter tests that confidence. Armed men from the tribe of Dan took his religious objects. They offered his priest a job serving their whole tribe, and the priest went with them. Micah protested, but the men threatened him. Seeing that they were stronger, he went home (Judges 18:14–26).

The story does not make the theft right. It shows how little protection Micah's arrangement gave him. The things he had gathered, and the priest he paid, could be carried away.

I see a warning here about treating faith as something I can arrange around my own wishes. A gift to a church does not buy God's agreement. A prayer before a decision does not mean I have listened for an answer I might dislike.

For me, listening begins with an honest question: am I willing to change course? I can read the passage that challenges me, hear the concern I would rather dismiss, and admit when a choice serves me at someone else's expense.

I still want to bring my hopes to God. I also want to leave room for correction. Faith can help me face an uncertain outcome without pretending I have purchased a certain one.

That is a different prayer from asking God to protect every plan I have already made.$pt$, $q$2026-10-25T21:00:00Z$q$, $q$future$q$, 48, null, null, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (2676, $q$Listen Before You Add to the Load$q$, $q$listen-before-you-add-to-the-load$q$, $pt$When someone tells me a task has become too much, I want to hear more than a complaint. They may be telling me something I cannot see from where I sit. If I have the power to change their workload, listening is part of my responsibility.

Rehoboam (ree-ho-BO-am) faced that choice when he succeeded his father, King Solomon, about 3,000 years ago. People gathered to make him king at Shechem (SHEE-kehm). The ancient city's site is near modern Nablus (NAH-blus) in the West Bank.

The people asked for relief from the harsh labor Solomon had required. They offered to serve the new king if he lightened their burden. Rehoboam asked them to return in three days while he sought advice (1 Kings 12:1–5).

His father's older advisers urged him to serve the people and answer their request favorably. But the men who had grown up with him urged a harsher reply. He chose their advice. When the people returned, he threatened to make their work even harder.

The account puts it plainly: “the king did not listen to the people” (1 Kings 12:15, NIV). The northern tribes rejected his rule. Rehoboam fled to Jerusalem, and the kingdom split (1 Kings 12:16–20).

I do not read this as a rule that older people are always right or younger people are always wrong. I notice what each group asked the king to do. One urged him to respond to the people's burden. The other urged him to increase it.

That gives me a useful question when I seek advice: does this help me understand the people affected, or only help me defend my decision?

At work, I could ask which task takes the most time before adding another deadline. At home, I could ask what needs to come off the list before asking someone to do more. Then I need to let the answer change something.

Listening does not mean I can grant every request. It does mean I can explain a real limit without treating the person who asked as a problem. I can name what I can change and follow through on it. A smaller promise kept can matter more than a quick reassuring answer.

Rehoboam had three days to consider his answer. I may have time to pause, too. Before I ask someone to carry more, I want to understand what they are already carrying.$pt$, $q$2026-10-18T21:00:00Z$q$, $q$future$q$, 49, null, null, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (2666, $q$An Apology Needs a Next Step$q$, $q$an-apology-needs-a-next-step$q$, replace($pt$When I hurt someone, saying I am sorry is a beginning. The person I hurt also has to live with what I do next. If I keep making the same choice, my words ask them to carry the cost of a change I have not made.

Manasseh (man-ASS-eh) was a king of Judah, the small kingdom centered on Jerusalem. He ruled in the seventh century BC, more than 2,600 years ago. The city remains in the same hills today.

His story includes terrible harm. He brought the worship of other gods into God's temple. He sacrificed his children and caused the deaths of innocent people. These were acts with victims, not just errors in judgment (2 Chronicles 33:3–6[[semicolon]] 2 Kings 21:16).

The book of Chronicles says God warned Manasseh and his people, but they did not listen. An invading army captured him and took him to Babylon. That ancient city's ruins are in modern Iraq, about 53 miles south of Baghdad.

In captivity, Manasseh asked God for help. The account says he “humbled himself greatly” (2 Chronicles 33:12, NIV). God heard his prayer and brought him back to Jerusalem.

Then his actions began to change. He removed the idols and the altars he had built for other gods. He restored the Lord's altar and called the people to worship God (2 Chronicles 33:15–16).

That change matters. So do the lives he had already harmed. His return could not make those deaths unhappen. The book of Kings keeps his violence in the record. I do not want to rush past those people to reach a comfortable ending.

What I see in Manasseh is a reason to stop defending a wrong choice. I can admit what I did without first finding someone whose actions were worse. I can ask God for mercy and still accept responsibility for repair.

For me, that might mean correcting a false statement in front of the people who heard it. It might mean returning money, changing a decision, or asking what would help without demanding an immediate answer. The next step should address the actual harm.

The person I hurt may need time or distance. My apology does not give me the right to set their timetable for trust.

I cannot rewrite what happened. I can stop adding to it. That is where I want an apology to become visible: in a different choice, made again when no one is applauding.$pt$, '[[semicolon]]', chr(59)), $q$2026-10-11T21:00:00Z$q$, $q$future$q$, 50, null, null, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (2656, $q$Remember Who Helped You$q$, $q$remember-who-helped-you$q$, $pt$I want to notice the people whose daily work makes my life possible. A meal, a finished project, a safe place to sleep: someone helped make each of those happen. When I forget that help, I can start treating everything I have as something I produced alone.

Nabal (NAY-bul) was a wealthy livestock owner in ancient Judah. His sheep were being sheared at Carmel (KAR-mul), a town usually identified with a site about eight miles south-southeast of Hebron (HEE-brun), in today's West Bank.

David, who would later become Israel's king, was living in the wilderness with his followers. They had helped protect Nabal's shepherds. At shearing time, David sent men to ask Nabal for food. He invited Nabal to check with his own workers about the help they had received (1 Samuel 25:4–8).

Nabal refused and insulted David. In his reply, he spoke of “my bread and water” and the meat prepared for his workers (1 Samuel 25:11, NIV). His answer made no room for the people who had helped keep his flocks safe.

David responded by preparing an armed attack. Nabal's insult did not excuse that choice. People throughout the household were now in danger.

One servant went to Nabal's wife, Abigail (AB-ih-gayl). He described the protection David's men had given them. She gathered food, met David, and urged him to stop. David accepted her appeal and turned back (1 Samuel 25:14–35).

While she was preventing bloodshed, Nabal was holding a feast. He did not learn what had happened until morning. The account ends with his death about ten days later (1 Samuel 25:36–38).

I do not read this as a promise that every refusal will bring disaster. What stays with me is how much Nabal's workers knew that his answer ignored. He had people nearby who could have helped him see the whole picture.

Before I decide that someone wants too much, I can ask what they have already contributed. Before I take credit, I can name the person who did the work. A thank-you becomes more useful when it is specific, and when fair treatment follows it.

I can still have limits. I cannot meet every request. But I want my answer to begin with an honest picture of what I have received. Remembering who helped me is one way to keep gratitude from becoming just a word.$pt$, $q$2026-10-04T21:00:00Z$q$, $q$future$q$, 51, null, null, null, null, null, $q$Nabal$q$, $q$done_before$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (2642, $q$Let Someone Tell You the Truth$q$, $q$let-someone-tell-you-the-truth$q$, $pt$I want the people I lead to be safe telling me when I am wrong. If keeping my respect means hiding a problem, my position has become part of the problem. I need someone who cares enough to speak, and I need to make room to listen.

Nathan (NAY-thun) was a prophet, someone who delivered God's messages. He advised David, the king of ancient Israel. Their story takes place in Jerusalem, the city that still stands in the hills about 32 miles east of the Mediterranean coast.

David had slept with Bathsheba (bath-SHEE-buh), another man's wife. When she became pregnant, David tried to hide what he had done. He then arranged for her husband, Uriah (you-RYE-uh), to die in battle. Afterward, David took her as his wife (2 Samuel 11).

God sent Nathan to confront him. Nathan began with a story about a rich man who owned many animals. A poor neighbor had one lamb, raised with his children and loved like part of the family. When a visitor arrived, the rich man took the poor man's lamb for the meal instead of using his own (2 Samuel 12:1–4).

David was furious. He could see the cruelty in someone else's choice.

Then Nathan said, “You are the man!” (2 Samuel 12:7, NIV).

Nathan named what David had done. The king's power did not remove his responsibility. David admitted his sin. Nathan told him that God had forgiven him, but serious consequences would follow (2 Samuel 12:9–14).

That is what I find hard about this story. I can spot unfairness quickly when someone else is responsible. When a complaint points toward me, I can become more interested in explaining myself than understanding the hurt.

My choices are not David's choices. But I can still listen for the moment when my explanation becomes an excuse. Did I interrupt someone? Did I take credit for work I did not do? Did I make it costly to disagree with me?

I can start by asking a person I trust about one specific decision. Then I can let them finish. I can check what happened, acknowledge my part, and change what I do next. An apology matters more when the person I hurt can see the difference.

Nathan gave David a chance to face the truth. I want to welcome that chance before someone has to fight to be heard.$pt$, $q$2026-09-27T21:00:00Z$q$, $q$future$q$, 52, null, null, $q$https://sammons.substack.com/p/when-truth-feels-dangerous$q$, $q$When Truth Feels Dangerous$q$, $q$https://youtu.be/C_elMZW17Jk$q$, $q$Nathan$q$, $q$done_before$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (2627, $q$Smart Don't Mean Good$q$, $q$smart-dont-mean-good$q$, replace($pt$I want my advice to help people, not just help someone win. That means asking why a plan matters before working out how to make it succeed. A smart plan can still hurt someone.

Ahithophel (uh-HITH-uh-fel) helped David, the king of ancient Israel, make hard choices. People trusted his advice. But when David's son tried to take the throne, Ahithophel chose the son's side (2 Samuel 15:12).

The son's name was Absalom (AB-suh-luhm). He wanted to replace his father as king. David fled Jerusalem, and Absalom entered the city with his followers. This was the same Jerusalem we can find today, in the hills about 32 miles east of the Mediterranean coast.

Ahithophel had a plan. He would take twelve thousand men and chase David that night. David was tired and weak. Ahithophel would kill him and bring his followers back to Absalom. The leaders who heard the plan liked it (2 Samuel 17:1–4).

The man who once helped David now offered to hunt him down.

But another adviser spoke. Hushai (HOO-shy) was David's friend. David had sent him back to work against Ahithophel's advice. Hushai urged Absalom to wait, gather more soldiers, and lead the army himself. Absalom chose his plan instead (2 Samuel 15:34[[semicolon]] 17:5–14).

The Bible says God had decided to stop “the good advice of Ahithophel” (2 Samuel 17:14, NIV).

That phrase can be confusing. Here, I understand “good” to mean the plan could work. It does not mean killing David was right. Ahithophel knew how to win. He was using that skill to help a son kill his father.

I can see a smaller version of that problem in daily life. A sharp reply might win an argument and wound a friend. Leaving someone out might make a project easier and cost that person a fair chance. Getting the result I want does not settle whether I should want it.

So before I offer advice, I need to name the purpose. Who would this help? Who might it hurt? Would I still support it if I were the person paying the price?

Those questions give me a way to pause. I can change the goal, suggest a kinder path, or refuse to help with harm.

I want to bring more than a clever answer to the table. I want a reason for giving it that I can stand behind.$pt$, '[[semicolon]]', chr(59)), $q$2026-09-20T21:00:00Z$q$, $q$publish$q$, 53, $q$https://stevesammons.com/smart-dont-mean-good/$q$, $q$https://sammons.substack.com/p/a-smart-plan-can-still-be-wrong$q$, $q$https://sammons.substack.com/p/the-dangerous-gap-between-smart-and$q$, $q$The Dangerous Gap Between Smart and Good$q$, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1907, $q$The Prayer That Worked$q$, $q$the-prayer-that-worked$q$, $pt$Hezekiah is around forty years old, fourteen years into his reign, when Isaiah walks in with a message that has no conditions attached to it. Put your house in order. You are going to die. You will not recover (2 Kings 20:1).

Hezekiah turns his face to the wall and prays. It is a short prayer, and it is about his record: remember how I have walked before you faithfully and with wholehearted devotion (2 Kings 20:3). Then he weeps bitterly.

Isaiah does not make it out of the middle court before God turns him around. I have heard your prayer. I have seen your tears. Fifteen years (2 Kings 20:4-6).

That is usually where this story gets told from, and it should be. A stated outcome undone by one man weeping at a wall. I have no interest in shrinking that.

But keep reading, because the failures the text lingers on all happen inside those fifteen years.

The Babylonians came because he got well. The delegation arrived with congratulations on his recovery, and he walked them through the whole treasury, and Isaiah told him what it would cost: all of it carried off to Babylon, and his own descendants with it, to serve in a foreign palace (2 Kings 20:17-18).

Hezekiah's answer is the part I had to read twice. "The word of the LORD you have spoken is good." Because he thought: there will be peace and security in my lifetime (2 Kings 20:19).

He heard that his grandchildren would be hauled off in chains and filed it under good news, because the dates worked out.

Manasseh was born in there too. He was twelve when Hezekiah died (2 Kings 21:1), which on a plain reading of the numbers puts his birth about three years into the extension. He went on to reign fifty-five years and take apart most of what his father built.

The Chronicler, who is never shy, names it exactly. Not "he sinned later." This: "Hezekiah's heart was proud and he did not respond to the kindness shown him" (2 Chronicles 32:25).

He does get the last word, and it's a mercy. Hezekiah repented of the pride of his heart, and the judgment was held back for the rest of his life (2 Chronicles 32:26).

Real repentance. It just came after the tour.

I was thirty-five when a doctor told me I had months.

My prayers got very small after that, and very specific. Please let me live. That was the whole prayer. I was not asking for wisdom about the time or clarity about what I'd do with it. I was asking to have it.

It was granted.

And it arrived the way it arrived for Hezekiah. No handbook. Nobody sat me down afterward to explain what the extra years were for, or what I now owed, or how a person is supposed to carry something like that. I got the years and I got the same silence he got.

Which is why the Chronicler's line is the one that gets me. He did not respond to the kindness shown him. That is not a failure I would have thought to watch for in myself. It doesn't feel like a failure. It feels like going back to work.

I don't have to imagine what Hezekiah prayed with his face to that wall. I know what I prayed with my face to mine. Same prayer.

The asking turned out to be the easy part.

I've had a lot of years since. The question I'm still working on is not whether I wanted them.$pt$, $q$2026-09-13T21:00:00Z$q$, $q$publish$q$, 54, $q$https://stevesammons.com/the-prayer-that-worked/$q$, $q$https://sammons.substack.com/p/the-prayer-that-worked$q$, $q$https://sammons.substack.com/p/what-do-we-owe-the-years-we-were$q$, $q$What Do We Owe the Years We Were Given?$q$, $q$https://youtu.be/Z7MxXz8HG2A$q$, $q$Hezekiah$q$, $q$done_before$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1875, $q$When Outcomes Stop Mattering$q$, $q$when-outcomes-stop-mattering$q$, $pt$They (Shadrach, Meshach, & Abednego) were teenagers when Babylon took them — maybe fifteen, marched out of Jerusalem with the rest of the useful boys. Twenty years later they were middle-aged men running a province for the king who took them. Foreign administrators in a foreign government, loyal to their captors and faithful to their God. They had careers by then. They had something to lose.

Then Nebuchadnezzar built a statue ninety feet tall and called the whole administration out to the plain of Dura.

When the music played, everyone bowed. The penalty for standing was fire.

Three men stayed on their feet.

Here's where it gets interesting. The king offered them a second chance — bow now, or burn — and mocked their God on the way out: "What god will be able to rescue you from my hand?" (Daniel 3:15).

Their answer is the whole story.

"We do not need to defend ourselves before you. If we are thrown into the fire, the God we serve is able to deliver us. But even if he does not, we will not serve your gods" (Daniel 3:16–18).

Even if he does not.

I make most of my decisions on expected outcomes. I run the odds. I hedge. I commit with an exit already picked out.

These three cut the outcome out of it. Their obedience wasn't priced against God's intervention. They weren't betting on a rescue. They were saying who they were.

The furnace got heated seven times hotter. The soldiers who carried them died at the mouth of it. Then there was a fourth figure walking in the flames (Daniel 3:25), and the three came out with their clothes intact and no smell of smoke on them. Hebrews 11:34 remembers them as the ones who "quenched the fury of the flames."

They couldn't have known any of that was coming. The miracle came after the commitment, not before.

That fourth figure is the part I keep sitting with. Not someone who kept them out of the fire. Someone who was in it with them.

The decisions that have defined me are the ones where I couldn't see the ending. Making the right call when it's guaranteed to work has never cost me anything, and it has never told me anything about myself either.

"Even if he does not" is the posture of someone who already did the math. Counted the cost. Accepted the worst case. Decided their integrity outweighed their survival.

That's not recklessness. That's clarity.

When you take the outcome out of the equation, you find out what you actually believe.$pt$, $q$2026-09-06T21:00:00Z$q$, $q$publish$q$, 55, $q$https://stevesammons.com/when-outcomes-stop-mattering/$q$, $q$https://sammons.substack.com/p/when-outcomes-stop-mattering$q$, $q$https://sammons.substack.com/p/when-faithfulness-cannot-see-the$q$, $q$When Faithfulness Cannot See the Ending$q$, null, $q$Shadrach, Meshach, and Abednego$q$, $q$done_before$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1952, $q$When Doubt Steals Your Voice$q$, $q$when-doubt-steals-your-voice$q$, $pt$He had prayed for a son every day of his adult life.

Zechariah was an old priest, married to Elizabeth, and they were well past the age where the prayer made any practical sense. His division served at the temple two weeks out of the year. The incense offering was assigned by lot, and with hundreds of priests in the rotation, most got one turn in a lifetime. Plenty got none at all.

That morning the lot fell to him (Luke 1:9).

The single most sacred moment of his career. And while he's standing there in the Holy Place, an angel appears at the right side of the altar. Gabriel himself. "Your prayer has been heard. Your wife Elizabeth will bear you a son."

Zechariah's response?

"How can I be sure of this?" (Luke 1:18)

Wait.

He prayed for this. For decades. And now he's asking for proof.

Gabriel doesn't argue. He takes the man's voice. Nine months of silence.

That struck me as harsh, until I sat with it a while.

Zechariah's doubt wasn't curiosity. It was the thing I do — ask for something, then act surprised when it shows up. I've prayed for a door to open and then stood in the doorway questioning whether I was ready to walk through it. I've asked for the opportunity and spent the first week checking to see whether it was real.

The silence wasn't punishment. I've come to think it was an invitation.

Nine months to stop talking and start trusting. Nine months to watch the impossible unfold in his own house — Elizabeth further along every week, and no way to explain it to a soul. Nine months to get ready for what he'd been asking for all along.

When the boy was born, the neighbors assumed he'd carry his father's name. Elizabeth said no. John. They turned to the old man and handed him a tablet.

He wrote: "His name is John" (Luke 1:63).

His voice came back that instant.

But he wasn't the same man. The first words out of his mouth weren't complaints, and they weren't questions. They were worship — a prophecy spoken over the baby about preparing the way (Luke 1:67-79).

The silence had done its work.

Here's what I'm learning. My biggest obstacle usually isn't getting the thing I asked for. It's believing it when it arrives.

Sometimes the forced pause is what gets you ready to receive it.$pt$, $q$2026-08-30T21:00:00Z$q$, $q$publish$q$, 56, $q$https://stevesammons.com/when-doubt-steals-your-voice/$q$, $q$https://sammons.substack.com/p/when-doubt-steals-your-voice$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (2508, $q$She Named the Place, Not the Answer$q$, $q$she-named-the-place-not-the-answer$q$, $pt$Hannah didn't name her son for the gift. She named him for the asking. I've come to think a good name is a receipt, not a wish.

Hannah was childless, in an ordinary household in the hill country of Ephraim (about twenty miles north of Jerusalem), around 1100 BC. She prayed at Shiloh — 1 Samuel 1.

STORY

A woman stands at the doorpost of the tent shrine at Shiloh, lips moving, no sound coming out. The old priest watches her mouth for a while and decides she's drunk.

She isn't. She's saying the truth to the only one who can do anything about it. Eli hears her out and blesses her.

Then the verse I keep going back to: "she went her way and ate something, and her face was no longer downcast" (1 Samuel 1:18).

She isn't pregnant. Nothing has been delivered. That's the part I can't get past — the gratitude arrived before the answer did.

When the boy comes, she names him Samuel: because I asked the LORD for him (1 Samuel 1:20). Not a hope. Not an ancestor. She named him for the request, so that anyone who said his name repeated the prayer out loud without knowing it.

My daughter-in-law is named Hannah.

She and my stepson prayed for a baby for years. Our whole family prayed alongside them.

They named her Shiloh Ray.

Shiloh for the prayer. Ray for my father.

It took me a beat to see it. A woman named Hannah named her daughter after the place where the first Hannah prayed for a child.

Three thousand years apart, and neither one named the baby for the answer. Both reached back and named her for the asking.

Shiloh isn't a name that means we got what we wanted. It's the name of a doorpost where a woman said a true thing out loud and was heard.

Her name faces backward — a prayer, and my father. We're thankful for the answer, and we're watching for what God has in store for Shiloh Ray.

You can name a child for what you hope she'll become. Or you can name her for what it took to get her here.

Names mean things. This one means a bunch.$pt$, $q$2026-08-23T21:35:13Z$q$, $q$publish$q$, 57, $q$https://stevesammons.com/she-named-the-place-not-the-answer/$q$, $q$https://sammons.substack.com/p/she-named-the-place-not-the-answer$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1903, $q$When Nobody Is Left to Tell You No$q$, $q$when-nobody-is-left-to-tell-you-no$q$, $pt$Most of us do not need more people who agree with us. We need at least one person who can tell us the truth when agreement would be easier.

That becomes harder as our influence grows. A leader may have advisers, employees, friends, and family nearby and still have no one who feels free to say, “You are wrong.”

King David learned the value of that voice after committing adultery with Bathsheba and arranging the death of her husband, Uriah. The prophet Nathan came to him with a story about a rich man who stole a poor man’s only lamb. David was furious at the injustice. Then Nathan made the story personal: “You are the man!” (2 Samuel 12:7).

Nathan’s words carried risk. David had already used his power to hide what he had done. Yet Nathan spoke, David confessed, and the truth interrupted the cover-up.

David’s son Solomon later became famous for wisdom. He organized a large government, built the temple in Jerusalem, and drew visitors from other nations. First Kings even records the names and jobs of his chief officials (1 Kings 4:1–6).

But success did not protect Solomon from drift. Early in his reign, he married the daughter of Egypt’s pharaoh as part of a political alliance (1 Kings 3:1). Later he accumulated many foreign wives, worshiped other gods, and ignored repeated warnings (1 Kings 11:1–10). After his death, the kingdom split.

The Bible does not say that Solomon lacked honest advisers. Still, the contrast makes me stop. David’s worst failure was met by a person who stood in the room and named it. In Solomon’s long decline, Scripture records warnings, but no similar scene of a trusted person breaking through.

That raises uncomfortable questions for us. Who can challenge a decision before it becomes a pattern? When did we last change course because someone spoke honestly? What happened to the last person who disagreed with us?

We may say we welcome correction. The people around us learn the truth by watching our response. If disagreement brings punishment, distance, or ridicule, silence will soon look safer.

Wisdom is not only knowing what to do. Sometimes it is giving another person enough standing to tell us what we cannot see—and enough safety to keep telling us.

That kind of honesty is worth protecting.$pt$, $q$2026-08-16T21:00:00Z$q$, $q$publish$q$, 58, $q$https://stevesammons.com/when-nobody-is-left-to-tell-you-no/$q$, $q$https://sammons.substack.com/p/when-nobody-is-left-to-tell-you-no$q$, null, null, null, $q$Solomon$q$, $q$done_before$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1886, $q$Leave the Stage for One$q$, $q$leave-the-stage-for-one$q$, $pt$BIG IDEA

What if the day you're needed most is the day God tells you to leave?

I chase scale. I measure impact by crowd size.

But the moment that outlived Philip came when he walked away from the crowd—for one person on an empty road.

BACKGROUND

Philip was a first-century leader, chosen to help distribute food to the widows of the early church (Acts 6:5). Later he's known simply as "the evangelist" (Acts 21:8).

His story exposed something I'd missed about influence.

STORY

Picture it. A city is buzzing. Crowds gather daily. Lives are changing.

Philip is in Samaria (modern-day West Bank, near Nablus). The momentum is electric (Acts 8:5–8).

Everything a leader dreams of is happening.

Then an angel of the Lord speaks. Go south—to the desert road that runs from Jerusalem down toward Gaza (modern-day Gaza Strip, on the coast) (Acts 8:26).

Wait—what?

Leave the revival?

Walk away from the crowds?

Trade the stage for a dusty road and a stranger?

He goes.

No fanfare. No crowd. Just Philip—and then the Spirit tells him to run to a passing chariot (Acts 8:29–30).

Inside sits an Ethiopian official (from the kingdom of Kush, in modern-day Sudan). Powerful. Searching. Puzzling over a scroll of Isaiah he can't unlock.

Philip climbs in.

They talk.

The official believes, and is baptized right there on the road (Acts 8:35–38).

THE TWIST

Here's what I missed.

That one conversation carried the gospel toward Africa. Tradition holds the Ethiopian church traces its roots to this encounter. Years later, Philip's own four daughters would prophesy in his home (Acts 21:9). The obedience he lived on that desert road became the air they grew up breathing.

But Philip couldn't have known any of that.

He didn't leave Samaria thinking, I'm about to reach a continent. He didn't climb into that chariot to change generations. He climbed in because God said go—and he went. The ripple was never his to see.

That's the part that stops me.

I used to think obedience was about the outcome—the crowd, the continent, the story someone tells later. It isn't. In the moment, the outcome was never mine to hold.

Have I lived my own small version of this? I don't know. I may never know whether the conversations and relationships I'm in will change anything for the generations after me. But when I look in the rearview mirror, I can see the hand of God. Miracles, worked through ordinary moments. In the moment, though? They felt like normal conversations. Nothing electric. Nothing that announced itself.

Maybe that's the point for me. Be obedient in the moment. Leave the rest up to God.

My friend Clare De Graaf wrote a whole book on this—The 10-Second Rule. The idea is simple: when you sense God nudging you toward something, do the next thing you're reasonably sure He's asking—within ten seconds, before you talk yourself out of it. Not because you can see where it leads. Because He asked.

Philip had his ten seconds on a desert road.

The crowd in Samaria? Others came to serve them—Peter and John followed close behind (Acts 8:14).

The man on the desert road? Only Philip was there.

This one person changed history—though Philip never lived to see how far it went.

Maybe today's interruption isn't a distraction from the call.

Maybe—when it's God who redirects me—it's the whole point.

I don't need to see the ripple. I need to be obedient in the moment… it makes me think.$pt$, $q$2026-08-02T21:00:00Z$q$, $q$publish$q$, 59, $q$https://stevesammons.com/leave-the-stage-for-one/$q$, $q$https://sammons.substack.com/p/leave-the-stage-for-one$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
insert into public.songs (post_id, post_title, slug, post_text, publish_date, post_status, priority, wordpress_url, substack_url, podcast_url, podcast_title, youtube_url, character, status) values (1905, $q$When the Manual Finally Shows Up$q$, $q$when-the-manual-finally-shows-up$q$, replace($pt$Do you remember your third-grade teacher's name?

Hold onto that picture for a second. A kid that age. Times tables. Recess. A backpack that's a little too big.

Now imagine this.

You're in third grade, and your dad gets killed — by the people who work for him. His own staff.

Then it gets stranger. The people of your town hunt down the ones who did it, and kill them too.

Now the part that rearranges your whole life: your dad was the king. Which means the job doesn't sit empty.

It's yours.

You. Third grade. Running a country.

One more thing you should know, because it matters. Your family has history. Your grandfather ran the place for fifty-five years, and he was, by every account, a bad dude — the kind who spends half a century tearing down the very thing the country was built on. And your father, the one who just got killed? Two years on the job, and already headed down the same road.

That's the family. That's the inheritance.

That's where Josiah starts.

Now roll the clock forward. He's twenty-six.

And here's what he's doing at twenty-six: he's running a renovation. The national temple — the most important building in the country — is getting restored. Rotten timber pulled out. Foundation repaired. Crews on payroll. Budget managed. Real, visible progress.

Then a worker finds something buried in the walls.

A scroll.

Not a memo. Not a copy of last year's plan. This was the founding document — the original charter that spelled out who these people were, what they were for, and how they had agreed to live. Every law. Every promise. The whole reason the nation existed in the first place.

It was the answer to "why are we even here," written down once, at the beginning — and then lost.

Missing for decades. Buried inside the very building built to hold it. Gone so long that when they finally read it out loud, there's a good chance not one person in that room had ever heard the words.

An entire nation had been running — collecting taxes, fighting wars, renovating its own temple — without the one document that told it who it was.

Josiah tears his clothes.

Not a figure of speech. He literally rips them.

Because it lands on him all at once: they hadn't just misplaced a book. They'd lost the plot. The building looked incredible, and nobody inside it could have told you what it was for anymore. The renovation was skin-deep. The drift went all the way to the bottom.

Here's what's easy to miss.

Josiah wasn't lazy. He wasn't asleep at the wheel. He was already doing good work. The renovation was real. People were employed. The budget balanced. The system ran.

But good work and right work aren't always the same thing.

I can run an efficient operation pointed in the wrong direction. I can polish a process that shouldn't exist. I can hit every number and miss the entire point.

This was my first corporate job, in the late 1980s — back when artists didn't have computers. That's almost impossible to picture now, but it's true. Computers were for accountants. A creative department ran on drawing boards, pencils, wax machines, and X-Acto knives.

So moving about three dozen board artists onto machines wasn't a software update. It was asking a room of people to give up their hands.

I took it seriously. I hired a consultant from my alma mater to run the transition — pulled her in from Art Center, where she was leading the exact same digital shift. We poured ourselves into their morale, their pace, the tablets that they would need, proper chairs to sit on because the board were being removed, whether the whole change would break them.

And with all that care, all that expertise in the room, I missed the most obvious thing. Production went to a standstill. They couldn't type.

I totally missed it.

I'd handed a team of career artists a tool they couldn't physically operate. So before we made a single beautiful thing on those Macs, they all went back to typing school.

That was my scroll. Not a vision. Not a strategy. Typing — the one thing so obvious I'd stepped right over it.

And that's the thing about a scroll. It rarely goes missing because it's rare. It goes missing because it's basic — because it sits underneath everything, which is exactly why you stop seeing it.

Josiah didn't have to go acquire anything new. The scroll was in the building the whole time. He just had to rediscover what was already his — and then find the guts to hold everything he'd built up against it.

So here's the only question that matters.

Not: are you busy?

Have you found the scroll?

Or better said, have I found the scroll?

Note: The whole story lives in two parallel accounts: 2 Kings 22–23 and 2 Chronicles 34–35. Chronicles tells it with a bit more detail on the reforms[[semicolon]] Kings is the tighter narrative.$pt$, '[[semicolon]]', chr(59)), $q$2026-07-26T21:00:00Z$q$, $q$publish$q$, 60, $q$https://stevesammons.com/when-the-manual-finally-shows-up/$q$, $q$https://sammons.substack.com/p/when-the-manual-finally-shows-up$q$, null, null, null, null, $q$waiting$q$)
on conflict (post_id) do update set post_title = excluded.post_title, slug = excluded.slug, post_text = excluded.post_text, publish_date = excluded.publish_date, post_status = excluded.post_status, priority = excluded.priority, wordpress_url = coalesce(excluded.wordpress_url, songs.wordpress_url), substack_url = coalesce(excluded.substack_url, songs.substack_url), podcast_url = coalesce(excluded.podcast_url, songs.podcast_url), podcast_title = coalesce(excluded.podcast_title, songs.podcast_title), youtube_url = coalesce(excluded.youtube_url, songs.youtube_url);
